# Example usage in `./workflows/reusable-e2e.yml`
name: Check Changed Packages
description: 'Checks whether any files in the specified packages were changed in the current commit'
inputs:
  commit:
    description: 'Commit to check files against'
    required: true
  packages:
    description: 'List of packages to check for changes, separated by new line'
    required: true
outputs:
  has-changed-packages:
    description: 'Boolean indicating whether any packages were changed'
    value: ${{ steps.check-changed-packages.outputs.has-changed-packages}}
runs:
  using: 'composite'
  steps:
    - name: Determine if there were changes in the given packages
      id: check-changed-packages
      shell: bash
      env:
        COMMIT_HASH: ${{ inputs.commit }}
        PACKAGES: ${{ inputs.packages }}
      run: |
        # stores the names of changed packages
        changed_packages=()
        changed_files=$(git diff-tree --no-commit-id --name-only -r $COMMIT_HASH)

        # concatenate input package names with pipe
        # input is on multiple lines so need :a;N;$!ba; to allow sed to read entire stream at once
        package_names=$(echo "$PACKAGES" | sed ':a;N;$!ba;s/\n/|/g')

        # check if any of the modified files belongs to the specified input packages
        if echo "$changed_files" | grep -Eq "^($package_names)/"; then
          echo "has-changed-packages=true" >> $GITHUB_OUTPUT
        else
          echo "has-changed-packages=false" >> $GITHUB_OUTPUT
        fi
