name: 'Set Status'
description: 'Set status on a specified head-sha'
inputs:
  context:
    description: 'Name of the status'
    required: true
  description:
    description: 'Short description of the status'
    required: false
  state:
    description: >-
      State of the status with possible values of 'error', 'failure', 'pending', 'success'
    required: true
  sha:
    description: 'The commit ID to add the status to'
    required: true
  target-url:
    description: >-
      Target URL to associate with this status.
      This URL will be linked from the GitHub UI to allow users to easily see the source of the status.'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Set a commit status
      id: set-status
      uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975 # v6.4.0 https://github.com/actions/github-script/commit/98814c53be79b1d30f795b907e553d8679345975
      env:
        status_context: ${{ inputs.context }}
        description: ${{ inputs.description }}
        state: ${{ inputs.state }}
        sha: ${{ inputs.sha }}
        target_url: ${{ inputs.target-url }}
        owner: ${{ github.event.repository.owner.login }}
        repo: ${{ github.event.repository.name }}
      with:
        result-encoding: string
        script: |
          const { status_context, description, state, sha, target_url, owner, repo } = process.env;
          let areInputsValid = true;
          const invalidInputs = [];
          if (state.length <= 0 || !['error', 'failure', 'pending', 'success'].includes(state)) {
            areInputsValid = false;
            invalidInputs.push('state');
          }
          if (context.length <= 0) {
            areInputsValid = false;
            invalidInputs.push('context');
          }
          if (sha.length <= 0) {
            areInputsValid = false;
            invalidInputs.push('sha');
          }
          if (areInputsValid) {
            github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha,
              state,
              context: status_context,
              description: description.length > 0 ? description : undefined,
              target_url: target_url.length > 0 ? target_url : undefined
            });
          } else {
            core.setFailed(`Value of ${invalidInputs.join(', ')} ${invalidInputs.length > 1 ? 'inputs are' : 'input is'} not valid`);
            return;
          }
