name: 'Update Status Checks'
description: 'Update status check on a specified check ID'
inputs:
  status:
    description: >-
      Status of check with possible values of 'queued', 'in_progress', 'completed'
    required: true
  check-id:
    description: 'Check ID of status check to be updated'
    required: true
  conclusion:
    description: >-
      Conclusion of status check with possible values of 'action_required',
      'cancelled', 'failure', 'neutral', 'success', 'skipped', 'stale', 'timed_out'.
      This is only required if status is 'completed'.
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975 # v6.4.0 https://github.com/actions/github-script/commit/98814c53be79b1d30f795b907e553d8679345975
      env:
        status: ${{ inputs.status }}
        check_run_id: ${{ inputs.check-id }}
        conclusion: ${{ inputs.conclusion }}
        owner: ${{ github.event.repository.owner.login }}
        repo: ${{ github.event.repository.name }}
      with:
        script: |
          const { status, conclusion, check_run_id, owner, repo } = process.env;
          github.rest.checks.update({
            owner,
            repo,
            status,
            check_run_id,
            conclusion: conclusion.length > 0 ? conclusion : undefined
          });
