export { default as DefaultAvatarExample } from './DefaultAvatarExample';
export { default as AvatarIconProviderExample } from './AvatarIconProviderExample';
export { default as AvatarSizeExample } from './AvatarSizeExample';
export { default as AvatarColorExample } from './AvatarColorExample';
export { default as AvatarVariationExample } from './AvatarVariationExample';
export { default as AvatarStyleExample } from './AvatarStyleExample';
export { default as AvatarThemeExample } from './AvatarThemeExample';
export { default as AvatarAccessibilityExample } from './AvatarAccessibilityExample';
export { default as AvatarLoadingExample } from './AvatarLoadingExample';
