enableGlobalCache: false

enableTelemetry: false

httpTimeout: 60000

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
  os:
    - current

packageExtensions:
  "@angular-devkit/build-angular@*":
    dependencies:
      minimatch: "3.0.5"
      webpack: "^5.76.0"

  "@size-limit/webpack@*":
    dependencies:
      webpack: "^5.76.0"

  "serve-handler@*":
    dependencies:
      minimatch: "3.0.5"
      path-to-regexp: "3.3.0"

  "codelyzer@*":
    dependencies:
      "@angular/core": "10.2.5"

  "next-plugin-preval@*":
    dependencies:
      webpack: "^5.76.0"
