enableGlobalCache: false

enableTelemetry: false

httpTimeout: 60000

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
  os:
    - current

packageExtensions:
  '@angular-devkit/build-angular@*':
    dependencies:
      webpack: '^5.94.0'

  '@size-limit/webpack@*':
    dependencies:
      webpack: '^5.94.0'

  'serve-handler@*':
    dependencies:
      path-to-regexp: '3.3.0'

  'codelyzer@*':
    dependencies:
      '@angular/core': '^14.3.0'

  'next-plugin-preval@*':
    dependencies:
      webpack: '^5.94.0'
