
/** This file is automatically generated. Do not edit. */
import React from 'react';
export const IconFileUpload = (props) => {
	const {
		size,
		fill = "currentColor",
		ariaLabel,
		...rest
	} = props;
	return (
		<svg xmlns="http://www.w3.org/2000/svg" data-size={size} aria-label={ariaLabel} fill={fill} {...rest} viewBox="0 0 24 24" className="amplify-icon"><path d="M9 16h6v-6h4l-7-7-7 7h4zm-4 2h14v2H5z"/></svg>
	);
};