
/** This file is automatically generated. Do not edit. */
import React from 'react';
export const IconWebAsset = (props) => {
	const {
		size,
		fill = "currentColor",
		ariaLabel,
		...rest
	} = props;
	return (
		<svg xmlns="http://www.w3.org/2000/svg" data-size={size} aria-label={ariaLabel} fill={fill} {...rest} viewBox="0 0 24 24" className="amplify-icon"><path d="M19 4H5c-1.11 0-2 .9-2 2v12c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V6c0-1.1-.89-2-2-2zm0 14H5V8h14v10z"/></svg>
	);
};