/** This file is automatically generated. Do not edit. */
import classNames from 'classnames';
import React from 'react';

import { ComponentClassNames } from '../../shared/constants';

export const IconNotStarted = (props) => {
  const { className, size, fill = 'currentColor', ariaLabel, ...rest } = props;
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      enable-background="new 0 0 20 20"
      className={classNames(ComponentClassNames.Icon, className)}
      viewBox="0 0 20 20"
      data-size={size}
      aria-label={ariaLabel}
      fill={fill}
      {...rest}
    >
      <rect fill="none" height="20" width="20" x="0" y="0" />
      <path d="M10,3c-3.86,0-7,3.14-7,7s3.14,7,7,7s7-3.14,7-7S13.86,3,10,3z M9,13H8V7h1V13z M10,13V7l4,3L10,13z" />
    </svg>
  );
};
