
/** This file is automatically generated. Do not edit. */
import React from 'react';
export const IconHMobiledata = (props) => {
	const {
		size,
		fill = "currentColor",
		ariaLabel,
		...rest
	} = props;
	return (
		<svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" data-size={size} aria-label={ariaLabel} fill={fill} {...rest} viewBox="0 0 24 24" className="amplify-icon"><g><path d="M0,0h24v24H0V0z" fill="none"/></g><g><g><path d="M15,11H9V7H7v10h2v-4h6v4h2V7h-2V11z"/></g></g></svg>
	);
};