
/** This file is automatically generated. Do not edit. */
import React from 'react';
export const IconEast = (props) => {
	const {
		size,
		fill = "currentColor",
		ariaLabel,
		...rest
	} = props;
	return (
		<svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" data-size={size} aria-label={ariaLabel} fill={fill} {...rest} viewBox="0 0 24 24" className="amplify-icon"><rect fill="none" height="24" width="24"/><path d="M15,5l-1.41,1.41L18.17,11H2V13h16.17l-4.59,4.59L15,19l7-7L15,5z"/></svg>
	);
};