/** This file is automatically generated. Do not edit. */
import React from 'react';
export const IconTrendingFlat = (props) => {
  const { size = 'medium', fill = 'currentColor', ariaLabel, ...rest } = props;
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      data-size={size}
      aria-label={ariaLabel}
      fill={fill}
      {...rest}
      viewBox="0 0 24 24"
      className="amplify-ui-icon"
    >
      <path d="M22 12l-4-4v3H3v2h15v3z" />
    </svg>
  );
};
