/** This file is automatically generated. Do not edit. */
import React from 'react';
export const IconEMobiledata = (props) => {
  const { size = 'medium', fill = 'currentColor', ariaLabel, ...rest } = props;
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      enable-background="new 0 0 24 24"
      data-size={size}
      aria-label={ariaLabel}
      fill={fill}
      {...rest}
      viewBox="0 0 24 24"
      className="amplify-ui-icon"
    >
      <g>
        <path d="M0,0h24v24H0V0z" fill="none" />
      </g>
      <g>
        <g>
          <path d="M16,9V7H8v10h8v-2h-6v-2h6v-2h-6V9H16z" />
        </g>
      </g>
    </svg>
  );
};
