/** This file is automatically generated. Do not edit. */
import React from 'react';
export const IconBrightness_1 = (props) => {
  const { size = 'medium', fill = 'currentColor', ariaLabel, ...rest } = props;
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      data-size={size}
      aria-label={ariaLabel}
      fill={fill}
      {...rest}
      viewBox="0 0 24 24"
      className="amplify-ui-icon"
    >
      <circle cx="12" cy="12" r="10" />
    </svg>
  );
};
