
/** This file is automatically generated. Do not edit. */
import React from 'react';
export const IconFlashlightOn = (props) => {
	const {
		size,
		fill = "currentColor",
		ariaLabel,
		...rest
	} = props;
	return (
		<svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" data-size={size} aria-label={ariaLabel} fill={fill} {...rest} viewBox="0 0 24 24" className="amplify-icon"><g><path d="M0,0h24v24H0V0z" fill="none"/></g><g><g><rect height="3" width="12" x="6" y="2"/><path d="M6,7v1l2,3v11h8V11l2-3V7H6z M12,15.5c-0.83,0-1.5-0.67-1.5-1.5s0.67-1.5,1.5-1.5s1.5,0.67,1.5,1.5S12.83,15.5,12,15.5z"/></g></g></svg>
	);
};