name: 'Add Status Check'
description: 'Add status check on a specified head-sha'
inputs:
  name:
    description: 'Name of status check'
    required: true
  status:
    description: >-
      Status of check with possible values of 'queued', 'in_progress', 'completed'
    required: true
  head-sha:
    description: 'The commit ID to add the checks to'
    required: true
  conclusion:
    description: >-
      Conclusion of status check with possible values of 'action_required',
      'cancelled', 'failure', 'neutral', 'success', 'skipped', 'stale', 'timed_out'.
      This is only required if status is 'completed'.
    required: false
outputs:
  check-id:
    description: 'Check ID of status check'
    value: ${{ steps.create-check.outputs.result }}
runs:
  using: 'composite'
  steps:
    - name: Create a status check
      id: create-check
      uses: actions/github-script@98814c53be79b1d30f795b907e553d8679345975 # v6.4.0 https://github.com/actions/github-script/commit/98814c53be79b1d30f795b907e553d8679345975
      env:
        name: ${{ inputs.name }}
        head_sha: ${{ inputs.head-sha }}
        status: ${{ inputs.status }}
        conclusion: ${{ inputs.conclusion }}
        owner: ${{ github.event.repository.owner.login }}
        repo: ${{ github.event.repository.name }}
      with:
        result-encoding: string
        script: |
          const { name, head_sha, status, conclusion, owner, repo } = process.env;
          const { data } = await github.rest.checks.create({
            name,
            owner,
            repo,
            head_sha,
            status,
            conclusion: conclusion.length > 0 ? conclusion : undefined
          });
          return data.id;
