/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AmplifyButton: typeof import('./src/components/primitives/amplify-button.vue')['default']
    AmplifyCheckBox: typeof import('./src/components/primitives/amplify-check-box.vue')['default']
    AmplifyTextField: typeof import('./src/components/primitives/amplify-text-field.vue')['default']
    BaseAlert: typeof import('./src/components/primitives/base-alert.vue')['default']
    BaseBox: typeof import('./src/components/primitives/base-box.vue')['default']
    BaseFieldSet: typeof import('./src/components/primitives/base-field-set.vue')['default']
    BaseFooter: typeof import('./src/components/primitives/base-footer.vue')['default']
    BaseForm: typeof import('./src/components/primitives/base-form.vue')['default']
    BaseFormField: typeof import('./src/components/primitives/base-form-field.vue')['default']
    BaseFormFields: typeof import('./src/components/primitives/base-form-fields.vue')['default']
    BaseHeading: typeof import('./src/components/primitives/base-heading.vue')['default']
    BaseInput: typeof import('./src/components/primitives/base-input.vue')['default']
    BaseLabel: typeof import('./src/components/primitives/base-label.vue')['default']
    BaseSelect: typeof import('./src/components/primitives/base-select.vue')['default']
    BaseSpacer: typeof import('./src/components/primitives/base-spacer.vue')['default']
    BaseText: typeof import('./src/components/primitives/base-text.vue')['default']
    BaseTwoTabItem: typeof import('./src/components/primitives/base-two-tab-item.vue')['default']
    BaseTwoTabs: typeof import('./src/components/primitives/base-two-tabs.vue')['default']
    BaseWrapper: typeof import('./src/components/primitives/base-wrapper.vue')['default']
    RenderInfo: typeof import('./src/components/primitives/render-info.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
