name: 'Log Metric'
description: 'Log data point to a metric with the provided value. If the metric is not there, it will create one.'
inputs:
  metric-name:
    description: 'target metric name'
    required: true
  value:
    description: 'the value to log to the metric'
    required: true
  AWS_ACCESS_KEY_ID:
    description: 'target AWS account credentials'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'target AWS account credentials'
    required: true
  AWS_REGION:
    description: 'target AWS account region'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.AWS_REGION }}
    - shell: bash
      run: aws cloudwatch put-metric-data --metric-name ${{ inputs.metric-name }} --namespace GithubCanaryApps --value ${{ inputs.value }}
