{
  /* DO NOT EDIT DIRECTLY */
}
{
  /* This file is autogenerated by "docs/scripts/generate-props-tables.ts" script. */
}
export const propdata = {
  displayName: 'Grid',
  mdnUrl: 'https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div',
  htmlElement: 'div',
  propsLists: [
    {
      name: 'Grid',
      props: [
        {
          name: 'area',
          isOptional: true,
          type: 'ResponsiveStyle<Property.GridArea>',
          description:
            "Specifies a grid item's size and location within a grid by contributing a line, a span, or nothing (automatic) to its grid placement, thereby specifying the edges of its grid area. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-area)",
        },
        {
          name: 'autoColumns',
          isOptional: true,
          type: 'ResponsiveStyle<Property.GridAutoColumns<0 | (string & {})>>',
          description:
            'Specifies the size of an implicitly-created grid column track or pattern of tracks. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-auto-columns)',
        },
        {
          name: 'autoFlow',
          isOptional: true,
          type: 'ResponsiveStyle<Property.GridAutoFlow>',
          description:
            'Controls how the auto-placement algorithm works, specifying exactly how auto-placed items get flowed into the grid. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-auto-flow)',
        },
        {
          name: 'autoRows',
          isOptional: true,
          type: 'ResponsiveStyle<Property.GridAutoRows<0 | (string & {})>>',
          description:
            'Specifies the size of an implicitly-created grid row track or pattern of tracks. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-auto-rows)',
        },
        {
          name: 'className',
          isOptional: true,
          type: 'string',
          description: 'Additional CSS class name for component',
        },
        {
          name: 'column',
          isOptional: true,
          type: 'ResponsiveStyle<Property.GridColumn>',
          description:
            "Specifies a grid item's size and location within a grid column by contributing a line, a span, or nothing (automatic) to its grid placement, thereby specifying the inline-start and inline-end edge of its grid area. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column)",
        },
        {
          name: 'columnEnd',
          isOptional: true,
          type: 'ResponsiveStyle<Property.GridColumnEnd>',
          description:
            "Specifies a grid item's end position within the grid column by contributing a line, a span, or nothing (automatic) to its grid placement, thereby specifying the block-end edge of its grid area. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column-end)",
        },
        {
          name: 'columnSpan',
          isOptional: true,
          type: "number | string | 'auto'",
          description:
            'Makes it possible for an element to span across all columns when its value is set to all. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/column-span)',
        },
        {
          name: 'columnStart',
          isOptional: true,
          type: 'ResponsiveStyle<Property.GridColumnStart>',
          description:
            "Specifies a grid item's start position within the grid column by contributing a line, a span, or nothing (automatic) to its grid placement. This start position defines the block-start edge of the grid area. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column-start)",
        },
        {
          name: 'id',
          isOptional: true,
          type: 'string',
          description: 'Unique identifier',
        },
        {
          name: 'isDisabled',
          isOptional: true,
          type: 'boolean',
          description:
            'Sets the Boolean &#96;disabled&#96; HTML attribute, which, when present, makes the element not mutable, focusable, or even submitted with the form',
        },
        {
          name: 'row',
          isOptional: true,
          type: 'ResponsiveStyle<Property.GridRow>',
          description:
            "Specifies a grid item's size and location within the grid row by contributing a line, a span, or nothing (automatic) to its grid placement, thereby specifying the inline-start and inline-end edge of its grid area. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-row)",
        },
        {
          name: 'rowEnd',
          isOptional: true,
          type: 'ResponsiveStyle<Property.GridRowEnd>',
          description:
            "Specifies a grid item's end position within the grid row by contributing a line, a span, or nothing (automatic) to its grid placement, thereby specifying the inline-end edge of its grid area. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-row-end)",
        },
        {
          name: 'rowSpan',
          isOptional: true,
          type: "number | string | 'auto'",
          description: '',
        },
        {
          name: 'rowStart',
          isOptional: true,
          type: 'ResponsiveStyle<Property.GridRowStart>',
          description:
            "Specifies a grid item's start position within the grid row by contributing a line, a span, or nothing (automatic) to its grid placement, thereby specifying the inline-start edge of its grid area. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-row-start)",
        },
        {
          name: 'style',
          isOptional: true,
          type: 'React.CSSProperties',
          description:
            'Accepts a JavaScript object with camelCased properties rather than a CSS string. This is consistent with the DOM style JavaScript property, is more efficient, and prevents XSS security holes. See: [React docs](https://reactjs.org/docs/dom-elements.html#style)',
        },
        {
          name: 'templateAreas',
          isOptional: true,
          type: 'ResponsiveStyle<Property.GridTemplateAreas>',
          description:
            'specifies named grid areas, establishing the cells in the grid and assigning them names. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-areas)',
        },
        {
          name: 'templateColumns',
          isOptional: true,
          type: 'ResponsiveStyle<Property.GridTemplateColumns<0 | (string & {})>>',
          description:
            'Defines the line names and track sizing functions of the grid columns. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns)',
        },
        {
          name: 'templateRows',
          isOptional: true,
          type: 'ResponsiveStyle<Property.GridTemplateRows<0 | (string & {})>>',
          description:
            'Defines the line names and track sizing functions of the grid rows. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-rows)',
        },
        {
          name: 'testId',
          isOptional: true,
          type: 'string',
          description:
            'Used to provide a &#96;data-testid&#96; attribute for testing purposes',
        },
      ],
      utilityProps: [
        {
          name: 'Layout',
          utilityProps: [
            {
              name: 'alignContent',
              isOptional: true,
              type: 'ResponsiveStyle<Property.AlignContent>',
              description:
                "Sets the distribution of space between and around content items along a flexbox's cross-axis or a grid's block axis. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/align-content)",
            },
            {
              name: 'alignItems',
              isOptional: true,
              type: 'ResponsiveStyle<Property.AlignItems>',
              description:
                'Sets the align-self value on all direct children as a group. In Flexbox, it controls the alignment of items on the Cross Axis. In Grid Layout, it controls the alignment of items on the Block Axis within their grid area. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/align-items)',
            },
            {
              name: 'area',
              isOptional: true,
              type: 'ResponsiveStyle<Property.GridArea>',
              description:
                "Specifies a grid item's size and location within a grid by contributing a line, a span, or nothing (automatic) to its grid placement, thereby specifying the edges of its grid area. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-area)",
            },
            {
              name: 'autoColumns',
              isOptional: true,
              type: 'ResponsiveStyle<Property.GridAutoColumns<0 | (string & {})>>',
              description:
                'Specifies the size of an implicitly-created grid column track or pattern of tracks. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-auto-columns)',
            },
            {
              name: 'autoFlow',
              isOptional: true,
              type: 'ResponsiveStyle<Property.GridAutoFlow>',
              description:
                'Controls how the auto-placement algorithm works, specifying exactly how auto-placed items get flowed into the grid. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-auto-flow)',
            },
            {
              name: 'autoRows',
              isOptional: true,
              type: 'ResponsiveStyle<Property.GridAutoRows<0 | (string & {})>>',
              description:
                'Specifies the size of an implicitly-created grid row track or pattern of tracks. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-auto-rows)',
            },
            {
              name: 'basis',
              isOptional: true,
              type: 'ResponsiveStyle<Property.FlexBasis<0 | (string & {})>>',
              description:
                'Default size of element before remaining space is distributed',
            },
            {
              name: 'column',
              isOptional: true,
              type: 'ResponsiveStyle<Property.GridColumn>',
              description:
                "Specifies a grid item's size and location within a grid column by contributing a line, a span, or nothing (automatic) to its grid placement, thereby specifying the inline-start and inline-end edge of its grid area. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column)",
            },
            {
              name: 'columnEnd',
              isOptional: true,
              type: 'ResponsiveStyle<Property.GridColumnEnd>',
              description:
                "Specifies a grid item's end position within the grid column by contributing a line, a span, or nothing (automatic) to its grid placement, thereby specifying the block-end edge of its grid area. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column-end)",
            },
            {
              name: 'columnGap',
              isOptional: true,
              type: 'ResponsiveStyle<SpaceKeys<StyleToken<Property.GridColumnGap<0 | (string & {})>>>>',
              description:
                'Controls the spacing between Flex/Grid child columns See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/column-gap)',
            },
            {
              name: 'columnSpan',
              isOptional: true,
              type: "number | string | 'auto'",
              description:
                'Makes it possible for an element to span across all columns when its value is set to all. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/column-span)',
            },
            {
              name: 'columnStart',
              isOptional: true,
              type: 'ResponsiveStyle<Property.GridColumnStart>',
              description:
                "Specifies a grid item's start position within the grid column by contributing a line, a span, or nothing (automatic) to its grid placement. This start position defines the block-start edge of the grid area. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-column-start)",
            },
            {
              name: 'flex',
              isOptional: true,
              type: 'ResponsiveStyle<Property.Flex<0 | (string & {})>>',
              description: 'Shorthand for flex grow / shrink / basis',
            },
            {
              name: 'gap',
              isOptional: true,
              type: 'ResponsiveStyle<SpaceKeys<StyleToken<Property.Gap<0 | (string & {})>>>>',
              description:
                'Controls the spacing between child components. Shorthand for rowGap and columnGap. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/gap)',
            },
            {
              name: 'grow',
              isOptional: true,
              type: 'ResponsiveStyle<Property.FlexGrow>',
              description: 'Ability for flex item to grow',
            },
            {
              name: 'justifyContent',
              isOptional: true,
              type: 'ResponsiveStyle<Property.JustifyContent>',
              description:
                'Defines how the browser distributes space between and around content items along the main-axis of a flex container, and the inline axis of a grid container. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content)',
            },
            {
              name: 'order',
              isOptional: true,
              type: 'ResponsiveStyle<Property.Order>',
              description:
                'Sets the order to lay out an item in a flex or grid container.',
            },
            {
              name: 'row',
              isOptional: true,
              type: 'ResponsiveStyle<Property.GridRow>',
              description:
                "Specifies a grid item's size and location within the grid row by contributing a line, a span, or nothing (automatic) to its grid placement, thereby specifying the inline-start and inline-end edge of its grid area. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-row)",
            },
            {
              name: 'rowEnd',
              isOptional: true,
              type: 'ResponsiveStyle<Property.GridRowEnd>',
              description:
                "Specifies a grid item's end position within the grid row by contributing a line, a span, or nothing (automatic) to its grid placement, thereby specifying the inline-end edge of its grid area. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-row-end)",
            },
            {
              name: 'rowGap',
              isOptional: true,
              type: 'ResponsiveStyle<SpaceKeys<StyleToken<Property.RowGap<0 | (string & {})>>>>',
              description:
                'Controls the spacing between Flex/Grid child rows See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/row-gap)',
            },
            {
              name: 'rowSpan',
              isOptional: true,
              type: "number | string | 'auto'",
              description: '',
            },
            {
              name: 'rowStart',
              isOptional: true,
              type: 'ResponsiveStyle<Property.GridRowStart>',
              description:
                "Specifies a grid item's start position within the grid row by contributing a line, a span, or nothing (automatic) to its grid placement, thereby specifying the inline-start edge of its grid area. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-row-start)",
            },
            {
              name: 'shrink',
              isOptional: true,
              type: 'ResponsiveStyle<Property.FlexShrink>',
              description: 'Ability for flex item to shrink',
            },
            {
              name: 'templateAreas',
              isOptional: true,
              type: 'ResponsiveStyle<Property.GridTemplateAreas>',
              description:
                'specifies named grid areas, establishing the cells in the grid and assigning them names. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-areas)',
            },
            {
              name: 'templateColumns',
              isOptional: true,
              type: 'ResponsiveStyle<Property.GridTemplateColumns<0 | (string & {})>>',
              description:
                'Defines the line names and track sizing functions of the grid columns. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns)',
            },
            {
              name: 'templateRows',
              isOptional: true,
              type: 'ResponsiveStyle<Property.GridTemplateRows<0 | (string & {})>>',
              description:
                'Defines the line names and track sizing functions of the grid rows. See: [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-rows)',
            },
          ],
        },
      ],
    },
  ],
};
