name: flutter_authenticator_example
description: amplify authenticator demo.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  amplify_flutter: ^1.0.0-0
  amplify_auth_cognito: ^1.0.0-0
  amplify_authenticator: ^1.0.0-0
  device_preview: ^1.0.0
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
