import { components } from './components';
import { ComponentStyles } from '../types';
import { Colors } from '@aws-amplify/ui/dist/types/theme/tokens/colors';

interface BaseTokens {
  colors: Partial<Colors>;
}

export interface Tokens extends BaseTokens {
  components: ComponentStyles;
}

// TODO: remove this and use the output generated by style-dictionary with different types
export const colors: Partial<Colors> = {
  brand: {
    primary: {
      10: { value: 'hsl(190, 75%, 95%)' },
      20: { value: 'hsl(190, 75%, 85%)' },
      40: { value: 'hsl(190, 70%, 70%)' },
      60: { value: 'hsl(190, 50%, 50%)' },
      80: { value: 'hsl(190, 95%, 30%)' },
      90: { value: 'hsl(190, 100%, 20%)' },
      100: { value: 'hsl(190, 100%, 15%)' },
    },
    secondary: {
      10: { value: 'hsl(300, 75%, 95%)' },
      20: { value: 'hsl(300, 75%, 85%)' },
      40: { value: 'hsl(300, 70%, 70%)' },
      60: { value: 'hsl(300, 50%, 50%)' },
      80: { value: 'hsl(300, 95%, 30%)' },
      90: { value: 'hsl(300, 100%, 20%)' },
      100: { value: 'hsl(300, 100%, 15%)' },
    },
  },
};

export const tokens: Tokens = {
  colors,
  components,
};
