export {
  FileUploader,
  FileUploaderHandle,
  FileUploaderProps,
  StorageImage,
  StorageImageProps,
  StorageManager,
  StorageManagerHandle,
  StorageManagerProps,
  DropZoneProps,
  ContainerProps,
  FileListProps,
  FilePickerProps,
  FileListHeaderProps,
  FileListFooterProps,
  // @TODO: temporary exports, should be exported from
  // '@aws-amplify/ui-react-storage/create-storage-browser'
  createAmplifyAuthAdapter,
  createManagedAuthAdapter,
  CreateManagedAuthAdapterInput,
  createStorageBrowser,
  CreateStorageBrowserInput,
  elementsDefault,
  ResolvedStorageBrowserElements,
  StorageBrowser,
  StorageBrowserAuthAdapter,
  StorageBrowserElements,
} from './components';
