module.exports = {
  alert: require('./alert'),
  badge: require('./badge'),
  button: require('./button'),
  card: require('./card'),
  divider: require('./divider'),
  flex: require('./flex'),
  heading: require('./heading'),
  icon: require('./icon'),
  image: require('./image'),
  pagination: require('./pagination'),
  placeholder: require('./placeholder'),
  rating: require('./rating'),
  text: require('./text'),
};
