export const SIGN_IN_TEXT = "Sign in to your account";
export const FULL_NAME_TEXT = "Full name";
export const AUTHENTICATOR = "Authenticator";
export const RESET_PASSWORD_LINK = "Reset Password";
export const NO_ACCOUNT = "No account?";
export const CREATE_ACCOUNT_LINK = "Create account";
export const SIGN_IN_BUTTON_TEXT = "Sign in";
export const FORGOT_YOUR_PASSWORD_TEXT = "Forgot your password?";
export const PASSWORD_LABEL = "Password";
