# Description: This workflow runs unit + e2e tests, then publishes UI packages
#              to a custom dist NPM tag of your choice. This is intended to run
#              on release branches (e.g. `in-app-messaging/release`).
#
# Triggered by: This runs whenever you push a commit to the specified release branch.
#
# To use: replace <BRANCH> with your release branch name. Replace <TAG> with
#         your NPM tag name.

name: Test and Publish / <BRANCH>

on:
  # You may change this to `pull_request` if you want to run this on a PRs.
  # This can be useful for publishing hotfixes quickly to unblock customers,
  # but otherwise, we recommend to use a release branch.
  push:
    branches: [<BRANCH>]

jobs:
  # You can skip tests based on your use case.
  test:
    uses: aws-amplify/amplify-ui/.github/workflows/reusable-e2e.yml@<BRANCH>
    with:
      commit: ${{ github.sha }}
      repository: ${{ github.repository }}
    secrets:
      AUTH_E2E_ROLE_ARN: ${{ secrets.AUTH_E2E_ROLE_ARN }}
      DATASTORE_E2E_ROLE_ARN: ${{ secrets.DATASTORE_E2E_ROLE_ARN }}
      GEO_E2E_ROLE_ARN: ${{ secrets.GEO_E2E_ROLE_ARN }}
      STORAGE_E2E_ROLE_ARN: ${{ secrets.STORAGE_E2E_ROLE_ARN }}
      IN_APP_MESSAGING_E2E_ROLE_ARN: ${{ secrets.IN_APP_MESSAGING_E2E_ROLE_ARN }}
      DOMAIN: ${{ secrets.DOMAIN }}
      PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
      USERNAME: ${{ secrets.USERNAME }}
      NEW_PASSWORD: ${{ secrets.NEW_PASSWORD }}
      VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
      SITE_URL: ${{ secrets.SITE_URL }}
      DOCSEARCH_DOCS_APP_ID: ${{ secrets.DOCSEARCH_DOCS_APP_ID }}
      DOCSEARCH_DOCS_API_KEY: ${{ secrets.DOCSEARCH_DOCS_API_KEY }}
      DOCSEARCH_DOCS_INDEX_NAME: ${{ secrets.DOCSEARCH_DOCS_INDEX_NAME }}

  publish:
    needs: test # remove this line if you're skipping test job.
    uses: ./.github/workflows/reusable-tagged-publish.yml
    with:
      dist-tag: <TAG>
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
