export enum LivenessClassNames {
  CameraModule = 'amplify-liveness-camera-module',
  CancelContainer = 'amplify-liveness-cancel-container',
  CancelButton = 'amplify-liveness-cancel-button',
  CountdownContainer = 'amplify-liveness-countdown-container',
  DescriptionBullet = 'amplify-liveness-description-bullet',
  DescriptionBulletIndex = 'amplify-liveness-description-bullet__index',
  DescriptionBulletIndexText = 'amplify-liveness-description-bullet__index__text',
  DescriptionBulletMessage = 'amplify-liveness-description-bullet__message',
  FadeOut = 'amplify-liveness-fade-out',
  FreshnessCanvas = 'amplify-liveness-freshness-canvas',
  InstructionOverlay = 'amplify-liveness-instruction-overlay',
  Loader = 'amplify-liveness-loader',
  OvalCanvas = 'amplify-liveness-oval-canvas',
  RecordingIconContainer = 'amplify-liveness-recording-icon-container',
  RecordingIcon = 'amplify-liveness-recording-icon',
  Video = 'amplify-liveness-video',
  VideoAnchor = 'amplify-liveness-video-anchor',
}
