export enum LivenessClassNames {
  CameraModule = 'amplify-liveness-camera-module',
  CancelContainer = 'amplify-liveness-cancel-container',
  CancelButton = 'amplify-liveness-cancel-button',
  CountdownContainer = 'amplify-liveness-countdown-container',
  DescriptionBullet = 'amplify-liveness-description-bullet',
  DescriptionBulletIndex = 'amplify-liveness-description-bullet__index',
  DescriptionBulletIndexText = 'amplify-liveness-description-bullet__index__text',
  DescriptionBulletMessage = 'amplify-liveness-description-bullet__message',
  FadeOut = 'amplify-liveness-fade-out',
  FreshnessCanvas = 'amplify-liveness-freshness-canvas',
  InstructionList = 'amplify-liveness-instruction-list',
  InstructionOverlay = 'amplify-liveness-instruction-overlay',
  Figure = 'amplify-liveness-figure',
  FigureCaption = 'amplify-liveness-figure__caption',
  FigureIcon = 'amplify-liveness-figure__icon',
  FigureImage = 'amplify-liveness-figure__image',
  Figures = 'amplify-liveness-figures',
  Loader = 'amplify-liveness-loader',
  MatchIndicator = 'amplify-liveness-match-indicator',
  OvalCanvas = 'amplify-liveness-oval-canvas',
  RecordingIconContainer = 'amplify-liveness-recording-icon-container',
  RecordingIcon = 'amplify-liveness-recording-icon',
  Toast = 'amplify-liveness-toast',
  Video = 'amplify-liveness-video',
  VideoAnchor = 'amplify-liveness-video-anchor',
}
