export { AuthenticatorProvider, AuthenticatorContext } from './context';
export {
  FooterComponent as AuthenticatorFooterComponent,
  FormFieldsComponent as AuthenticatorFormFieldsComponent,
  HeaderComponent as AuthenticatorHeaderComponent,
  isComponentRouteKey as isAuthenticatorComponentRouteKey,
  RouteComponentsDefaults as AuthenticatorRouteComponentsDefaults,
  RouteComponentsOverrides as AuthenticatorRouteComponentsOverrides,
  WebRouteComponentsDefaults as AuthenticatorWebRouteComponentsDefaults,
  AuthenticatorLegacyField,
  AuthenticatorMachineContext,
  AuthenticatorRouteComponentKey,
  AuthenticatorRouteComponentName,
  useAuthenticator,
  UseAuthenticator,
  useAuthenticatorComponents,
  useAuthenticatorInitMachine,
  useAuthenticatorProps,
  // Below to be removed
  DefaultProps as AuthenticatorComponentDefaultProps,
  Defaults as AuthenticatorComponentDefaults,
  Overrides as AuthenticatorComponentOverrides,
  resolveAuthenticatorComponents,
  useAuthenticatorRoute,
  UseAuthenticatorRoute,
} from './hooks';
