/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-west-2',
  aws_cognito_identity_pool_id:
    'us-west-2:87db9eea-59d5-4442-963d-f89a0c5c0482',
  aws_cognito_region: 'us-west-2',
  aws_user_pools_id: 'us-west-2_geByXhyXK',
  aws_user_pools_web_client_id: '5d2p89ikb8bmqs2mg1vfdjpsuu',
  oauth: {
    domain:
      's3cloudfronttest9141b45b-9141b45b-dev.auth.us-west-2.amazoncognito.com',
    scope: [
      'phone',
      'email',
      'openid',
      'profile',
      'aws.cognito.signin.user.admin',
    ],
    redirectSignIn: 'http://localhost:3001/oauth-sign-in/redirect/',
    redirectSignOut: 'http://localhost:3001/oauth-sign-in/redirect/',
    responseType: 'code',
  },
  federationTarget: 'COGNITO_USER_AND_IDENTITY_POOLS',
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: ['GOOGLE'],
  aws_cognito_signup_attributes: [],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['PHONE_NUMBER'],
  aws_user_files_s3_bucket:
    's3cloudfronttest5038cbe2998c480ea6a8e450630a2b0110857-dev',
  aws_user_files_s3_bucket_region: 'us-west-2',
  aws_dynamodb_all_tables_region: 'us-west-2',
  aws_dynamodb_table_schemas: [
    {
      tableName: 'v6nextjsapirestItem-dev',
      region: 'us-west-2',
    },
  ],
  aws_mobile_analytics_app_id: 'bf6e9ee69c7a4ab4bd7617281a95a3b8',
  aws_mobile_analytics_app_region: 'us-west-2',
  Analytics: {
    AWSPinpoint: {
      appId: 'bf6e9ee69c7a4ab4bd7617281a95a3b8',
      region: 'us-west-2',
    },
  },
  Notifications: {
    InAppMessaging: {
      AWSPinpoint: {
        appId: 'bf6e9ee69c7a4ab4bd7617281a95a3b8',
        region: 'us-west-2',
      },
    },
  },
  aws_cloud_logic_custom: [
    {
      name: 'v6nextjsapirest',
      endpoint: 'https://odehh9uin9.execute-api.us-west-2.amazonaws.com/dev',
      region: 'us-west-2',
    },
  ],
  aws_appsync_graphqlEndpoint:
    'https://wzqmbvqkeve4xiksjotm2awb2q.appsync-api.us-west-2.amazonaws.com/graphql',
  aws_appsync_region: 'us-west-2',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-gxpqt4wj4zegxhivb6yoabhg6e',
};

export default awsmobile;
