export * from './components';
export * from './hooks';
export * from './primitives';

export * as components from './components';
export * as primitives from './primitives';

export { theme } from './defaultTheme';

export {
  AmplifyAuthenticator,
  AmplifySignOut,
  AmplifyAmazonButton,
  AmplifyAuthContainer,
  AmplifyAuthFields,
  AmplifyAuth0Button,
  AmplifyButton,
  AmplifyChatbot,
  AmplifyCheckbox,
  AmplifyCodeField,
  AmplifyConfirmSignIn,
  AmplifyConfirmSignUp,
  AmplifyContainer,
  AmplifyCountryDialCode,
  AmplifyEmailField,
  AmplifyFacebookButton,
  AmplifyFederatedButtons,
  AmplifyFederatedSignIn,
  AmplifyForgotPassword,
  AmplifyFormField,
  AmplifyFormSection,
  AmplifyGoogleButton,
  AmplifyGreetings,
  AmplifyHint,
  AmplifyIcon,
  AmplifyIconButton,
  AmplifyInput,
  AmplifyLabel,
  AmplifyLink,
  AmplifyLoadingSpinner,
  AmplifyNav,
  AmplifyOauthButton,
  AmplifyPasswordField,
  AmplifyPhoneField,
  AmplifyPhotoPicker,
  AmplifyPicker,
  AmplifyRadioButton,
  AmplifyRequireNewPassword,
  AmplifyS3Album,
  AmplifyS3Image,
  AmplifyS3ImagePicker,
  AmplifyS3Text,
  AmplifyS3TextPicker,
  AmplifySection,
  AmplifySelect,
  AmplifySelectMfaType,
  AmplifySignIn,
  AmplifySignInButton,
  AmplifySignUp,
  AmplifyStrike,
  AmplifyToast,
  AmplifyTooltip,
  AmplifyTotpSetup,
  AmplifyUsernameField,
  AmplifyVerifyContact,
} from '@aws-amplify/ui-react-v1';
