/**
 * This file contains helpers related to forms and input attributes.
 */

import { countryDialCodes } from '../../i18n';

export const defaultFormFieldOptions = {
  birthdate: {
    label: 'Birthdate',
    labelHidden: false,
    placeholder: 'Birthdate',
    type: 'date',
    autocomplete: 'bday',
    isRequired: true,
  },
  confirmation_code: {
    label: 'Confirmation Code',
    labelHidden: false,
    placeholder: 'Code',
    type: 'number',
    autocomplete: 'one-time-code',
    isRequired: true,
  },
  confirm_password: {
    label: 'Confirm Password',
    labelHidden: false,
    placeholder: 'Confirm Password',
    type: 'password',
    autocomplete: 'new-password',
    isRequired: true,
  },
  email: {
    label: 'Email',
    labelHidden: false,
    placeholder: 'Email',
    type: 'email',
    autocomplete: 'username',
    isRequired: true,
  },
  family_name: {
    label: 'Family Name',
    labelHidden: false,
    placeholder: 'Family Name',
    type: 'text',
    autocomplete: 'family-name',
    isRequired: true,
  },
  given_name: {
    label: 'Given Name',
    labelHidden: false,
    placeholder: 'Given Name',
    type: 'text',
    autocomplete: 'given-name',
    isRequired: true,
  },
  middle_name: {
    label: 'Middle Name',
    labelHidden: false,
    placeholder: 'Middle Name',
    type: 'text',
    autocomplete: 'additional-name',
    isRequired: true,
  },
  name: {
    label: 'Name',
    labelHidden: false,
    placeholder: 'Name',
    type: 'text',
    autocomplete: 'name',
    isRequired: true,
  },
  nickname: {
    label: 'Nickname',
    labelHidden: false,
    placeholder: 'Nickname',
    type: 'text',
    autocomplete: 'tel',
    isRequired: true,
  },
  password: {
    label: 'Password',
    labelHidden: false,
    placeholder: 'Password',
    type: 'password',
    autocomplete: 'new-password',
    isRequired: true,
  },
  phone_number: {
    label: 'Phone Number',
    labelHidden: false,
    placeholder: 'Phone',
    type: 'tel',
    autocomplete: 'tel',
    dialCode: '+1',
    dialCodeList: countryDialCodes,
    isRequired: true,
  },
  preferred_username: {
    label: 'Preferred Username',
    labelHidden: false,
    placeholder: 'Preferred Username',
    type: 'text',
    isRequired: true,
  },
  profile: {
    label: 'Profile',
    labelHidden: false,
    placeholder: 'Profile',
    type: 'url',
    autocomplete: 'url',
    isRequired: true,
  },
  website: {
    label: 'Website',
    labelHidden: false,
    placeholder: 'Website',
    type: 'url',
    autocomplete: 'url',
    isRequired: true,
  },
  username: {
    label: 'Username',
    labelHidden: false,
    placeholder: 'Username',
    type: 'text',
    autocomplete: 'username',
    isRequired: true,
  },
} as const;
