/**
 * WARNING: Do not edit this file. Storybook overwrites the contents of this
 * file during the `prestorybook` setup step.
 *
 * The current contents are a placeholder to prevent the Example app from
 * crashing when running non-storybook apps.
 *
 * Updates to this file will be reverted by the husky pre-commit hook.
 */
module.exports = { loadStories: () => null };
