export const ACTIONS_CHANNEL = 'ui-actions';
export const ACTION_AUTH_SIGNOUT = 'AuthSignOut';
export const ACTION_NAVIGATE = 'Navigate';
export const ACTION_DATASTORE_CREATE = 'DataStoreCreate';
export const ACTION_DATASTORE_DELETE = 'DataStoreDelete';
export const ACTION_DATASTORE_UPDATE = 'DataStoreUpdate';

export const ACTION_STARTED = 'Started';
export const ACTION_FINISHED = 'Finished';

export const ACTION_AUTH_SIGNOUT_STARTED = `${ACTION_AUTH_SIGNOUT}_${ACTION_STARTED}`;
export const ACTION_AUTH_SIGNOUT_FINISHED = `${ACTION_AUTH_SIGNOUT}_${ACTION_FINISHED}`;

export const ACTION_NAVIGATE_STARTED = `${ACTION_NAVIGATE}_${ACTION_STARTED}`;
export const ACTION_NAVIGATE_FINISHED = `${ACTION_NAVIGATE}_${ACTION_FINISHED}`;

export const ACTION_DATASTORE_CREATE_STARTED = `${ACTION_DATASTORE_CREATE}_${ACTION_STARTED}`;
export const ACTION_DATASTORE_CREATE_FINISHED = `${ACTION_DATASTORE_CREATE}_${ACTION_FINISHED}`;
export const ACTION_DATASTORE_CREATE_STARTED_MESSAGE = `${ACTION_DATASTORE_CREATE} action ${ACTION_STARTED}`;
export const ACTION_DATASTORE_CREATE_FINISHED_MESSAGE = `${ACTION_DATASTORE_CREATE} action ${ACTION_FINISHED}`;

export const ACTION_DATASTORE_DELETE_STARTED = `${ACTION_DATASTORE_DELETE}_${ACTION_STARTED}`;
export const ACTION_DATASTORE_DELETE_FINISHED = `${ACTION_DATASTORE_DELETE}_${ACTION_FINISHED}`;
export const ACTION_DATASTORE_DELETE_STARTED_MESSAGE = `${ACTION_DATASTORE_DELETE} action ${ACTION_STARTED}`;
export const ACTION_DATASTORE_DELETE_FINISHED_MESSAGE = `${ACTION_DATASTORE_DELETE} action ${ACTION_FINISHED}`;
