import fs from 'fs';
import path from 'path';
import { globbyStream } from 'globby';
import { getCatalog } from './util/getCatalog';
import type {
  Catalog,
  Category,
  ComponentName,
  Properties,
} from './types/catalog';

const catalog = getCatalog();

// console.log(' 🐻 catalog: ', JSON.stringify(getCatalog(), null, 2));

createAllPropsTables();

async function createAllPropsTables() {
  for await (const componentFilepath of globbyStream(
    path.join(
      __dirname,
      '../../docs/src/pages/[platform]/components/*/index.page.mdx'
    )
  )) {
    const regex =
      /src\/pages\/\[platform\]\/components\/(\w*)\/index\.page\.mdx/;
    const componentPageName = (componentFilepath as string).match(
      regex
    )[1] as Lowercase<ComponentName>;
    const properties = getObjectValueWithCaselessKey(
      catalog,
      componentPageName
    )?.properties;
    const propsSortedByCategory = getPropsSortedByCategory(
      properties,
      componentPageName
    );

    if (!propsSortedByCategory) {
      console.log(`❗️ Not generating props table for ${componentPageName}`);
      continue;
    }

    const componentName = Object.keys(
      propsSortedByCategory[0]
    )[0] as ComponentName;

    const expander = PropsTableExpander(propsSortedByCategory);

    fs.writeFileSync(
      path.join(
        __dirname,
        '../../docs/src/pages/[platform]/components/',
        `./${componentPageName}/props-table.mdx`
      ),
      Output(componentName, expander)
    );
    console.log(`✅ ${componentPageName} Props Tables are updated.`);
  }
}

type CategoryProperty = { [key in Category]: Properties };
type SortedPropertiesByCategory = CategoryProperty[];
type PropertiesByCategory = Record<Category, Properties>;

function Output(displayName, tableExpander) {
  return `
{/* DO NOT EDIT DIRECTLY */}
{/* This file is autogenerated by "docs/scripts/generate-props-tables.ts" script. */}
{/* See Docs README to generate */}
import { Expander, ExpanderItem, Table, TableBody, TableCell, TableHead, TableRow } from '@aws-amplify/ui-react';

## ${displayName} Props

${tableExpander}
`;
}

function PropsTableExpander(propsSortedByCategory: SortedPropertiesByCategory) {
  const defaultOpen = Object.keys(propsSortedByCategory[0])[0];
  const expanderItem = (categoryProperty: CategoryProperty): string => {
    const title = Object.keys(categoryProperty)[0];
    const table = PropsTable(categoryProperty[title]);
    return `
<ExpanderItem title="${title}" value="${title}">
    ${table}
</ExpanderItem>
`;
  };

  return `
<Expander type="multiple" defaultValue={['${defaultOpen}']}>
  ${propsSortedByCategory.map(expanderItem).join('')}
</Expander>
`;
}

function PropsTable(properties: Properties) {
  const rows = Object.entries(properties).map(
    ([propName, { name, type, description }]) => `
    <TableRow>
      <TableCell className="props-table__tr-name">${name}</TableCell>
      <TableCell>${`
\`\`\`jsx
${type}
\`\`\`
`}</TableCell>
      <TableCell className="props-table__tr-description">${description}</TableCell>
    </TableRow>
`
  );
  return `
<Table
  highlightOnHover={true}
  className="props-table"
  >
  <TableHead>
    <TableRow>
      <TableCell as="th">Name</TableCell>
      <TableCell as="th">Type</TableCell>
      <TableCell as="th">Description</TableCell>
    </TableRow>
  </TableHead>
  <TableBody>
    ${rows.join('')}
  </TableBody>
</Table>
`;
}

function getPropsSortedByCategory(
  properties: Properties,
  componentPageName: Lowercase<ComponentName>
): SortedPropertiesByCategory {
  if (properties) {
    let propertiesByCategory: PropertiesByCategory = {} as PropertiesByCategory;

    for (const propertyName in getObjectValueWithCaselessKey(
      catalog,
      componentPageName
    ).properties) {
      const property = getObjectValueWithCaselessKey(catalog, componentPageName)
        .properties[propertyName];
      propertiesByCategory = {
        ...propertiesByCategory,
        [property.category]: {
          ...propertiesByCategory[property.category],
          [propertyName]: property,
        },
      };
    }

    const componentName =
      Object.keys(propertiesByCategory).find(
        (category) => category.toLowerCase() === componentPageName
      ) ?? (componentPageName as ComponentName | Lowercase<ComponentName>);

    const allCategories = [
      componentName,
      ...Object.keys(propertiesByCategory)
        .filter((category) => ![componentName, 'Other'].includes(category))
        .sort((a, b) => a.localeCompare(b)),
      // 'Other',  // 1. No need to show this category to the customers 2. It causes Amplify Hosting build memory leak
    ] as (Category | 'Other')[];

    return allCategories
      .map(
        (category) =>
          ({
            [category]: getObjectValueWithCaselessKey(
              propertiesByCategory,
              category
            ),
          } as {
            [key in Category]: Properties;
          })
      )
      .filter((val) => Object.values(val)[0]);
  } else {
    console.log(` 🫥  ${componentPageName} doesn't have any type properties.`);
    return null;
  }
}

/**
 *
 * @name getProperties
 * @description case-insensitively get the values from an object
 */
function getObjectValueWithCaselessKey(
  object: PropertiesByCategory,
  key:
    | ComponentName
    | Lowercase<ComponentName>
    | Category
    | Lowercase<Category>
    | 'Other'
): Properties;
function getObjectValueWithCaselessKey(
  object: Catalog,
  key:
    | ComponentName
    | Lowercase<ComponentName>
    | Category
    | Lowercase<Category>
    | 'Other'
): {
  properties: Properties;
};
function getObjectValueWithCaselessKey(object, key) {
  const asLowercase = key.toLowerCase();
  return object[
    Object.keys(object).find((k) => k.toLowerCase() === asLowercase)
  ];
}
