import { render, screen, fireEvent } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import * as React from 'react';

import { SliderField, RANGE, ROOT, TRACK } from '../SliderField';
import {
  testFlexProps,
  expectFlexContainerStyleProps,
} from '../../Flex/__tests__/Flex.test';
import { ComponentClassNames } from '../../shared/constants';
import { AUTO_GENERATED_ID_PREFIX } from '../../shared/utils';

// Jest uses JSDom, which apparently doesn't support the ResizeObserver API
// This will get around that API reference error in Jest
// We don't necessarily test its functionality since Radix should be responsible for that
window.ResizeObserver =
  window.ResizeObserver ||
  jest.fn().mockImplementation(() => ({
    disconnect: jest.fn(),
    observe: jest.fn(),
    unobserve: jest.fn(),
  }));

describe('SliderField: ', () => {
  describe('Flex wrapper', () => {
    it('should render all flex style props', async () => {
      render(
        <SliderField
          defaultValue={0}
          testId="slider-field"
          label="slider"
          {...testFlexProps}
        />
      );
      const sliderField = await screen.findByTestId('slider-field');
      expectFlexContainerStyleProps(sliderField);
    });
  });

  describe('Label', () => {
    it('should render expected field classname', async () => {
      render(<SliderField defaultValue={0} label="slider" />);

      const label = await screen.findByText('slider');
      expect(label.parentElement).toHaveClass(
        ComponentClassNames.Label,
        ComponentClassNames.SliderFieldLabel
      );
    });

    it('should have `sr-only` class when labelHidden is true', async () => {
      render(
        <SliderField defaultValue={0} label="slider" labelHidden={true} />
      );

      const label = await screen.findByText('slider');
      expect(label.parentElement).toHaveClass('sr-only');
    });

    it('should set id when id is provided', async () => {
      render(<SliderField label="slider" id="slider-field" />);
      const label = await screen.findByText('slider');
      expect(label.parentElement.id).toBe('slider-field');
    });

    it('should set autogenerated id when it is not provided, ', async () => {
      render(<SliderField label="slider" />);
      const label = await screen.findByText('slider');
      expect(
        label.parentElement.id.startsWith(AUTO_GENERATED_ID_PREFIX)
      ).toBeTruthy();
    });

    it('should display value if isValueHidden is false', async () => {
      render(<SliderField defaultValue={10} label="slider" />);
      const value = await screen.queryByText('10');
      expect(value).toBeInTheDocument();
    });

    it('should not display value if isValueHidden is true', async () => {
      render(<SliderField defaultValue={10} label="slider" isValueHidden />);
      const value = await screen.queryByText('10');
      expect(value).not.toBeInTheDocument();
    });
  });

  describe('Slider', () => {
    describe('Root', () => {
      it('should render default and custom classname', async () => {
        const className = 'class-test';
        render(
          <SliderField defaultValue={0} label="slider" className={className} />
        );
        const root = await screen.findByTestId(ROOT);
        expect(root).toHaveClass(
          ComponentClassNames.SliderFieldRoot,
          className
        );
      });

      it('should pass orientation prop', async () => {
        render(
          <SliderField defaultValue={0} label="slider" orientation="vertical" />
        );
        const root = await screen.findByTestId(ROOT);
        expect(root).toHaveAttribute('data-orientation', 'vertical');
      });

      it('should be disabled', async () => {
        render(<SliderField defaultValue={0} label="slider" isDisabled />);
        const root = await screen.findByTestId(ROOT);
        expect(root).toHaveAttribute('data-disabled', '');
      });
    });

    describe('Track', () => {
      it('should render default classname', async () => {
        render(<SliderField defaultValue={0} label="slider" />);
        const track = await screen.findByTestId(TRACK);
        expect(track).toHaveClass(ComponentClassNames.SliderFieldTrack);
      });

      it('should set empty track color', async () => {
        render(
          <SliderField defaultValue={0} label="slider" emptyTrackColor="red" />
        );
        const track = await screen.findByTestId(TRACK);
        expect(track).toHaveStyle('background-color: red');
      });

      it('should set track width for horizontal slider', async () => {
        render(
          <SliderField defaultValue={0} label="slider" trackWidth="3px" />
        );
        const track = await screen.findByTestId(TRACK);
        expect(track).toHaveStyle('height: 3px');
      });

      it('should set track width for vertical slider', async () => {
        render(
          <SliderField
            defaultValue={0}
            label="slider"
            orientation="vertical"
            trackWidth="3px"
          />
        );
        const track = await screen.findByTestId(TRACK);
        expect(track).toHaveStyle('width: 3px');
      });
    });

    describe('Range', () => {
      it('should render default classname', async () => {
        render(<SliderField defaultValue={0} label="slider" />);
        const range = await screen.findByTestId(RANGE);
        expect(range).toHaveClass(ComponentClassNames.SliderFieldRange);
      });

      it('should set filled track color', async () => {
        render(
          <SliderField
            defaultValue={0}
            label="slider"
            filledTrackColor="teal"
          />
        );
        const range = await screen.findByTestId(RANGE);
        expect(range).toHaveStyle('background-color: teal');
      });
    });

    describe('Thumb', () => {
      it('should render default classname', async () => {
        render(<SliderField defaultValue={0} label="slider" />);
        const thumb = await screen.findByRole('slider');
        expect(thumb).toHaveClass(ComponentClassNames.SliderFieldThumb);
      });

      it('should pass min and max props', async () => {
        render(
          <SliderField defaultValue={0} label="slider" min={-100} max={100} />
        );
        const thumb = await screen.findByRole('slider');
        expect(thumb).toHaveAttribute('aria-valuemin', '-100');
        expect(thumb).toHaveAttribute('aria-valuemax', '100');
      });

      it('should set thumb color', async () => {
        render(
          <SliderField defaultValue={0} label="slider" thumbColor="orange" />
        );
        const thumb = await screen.findByRole('slider');
        expect(thumb).toHaveStyle('background-color: orange');
      });

      it('should set aria-describedby', async () => {
        render(
          <SliderField defaultValue={0} label="slider" id="slider-field" />
        );
        const thumb = await screen.findByRole('slider');
        expect(thumb).toHaveAccessibleDescription('slider 0');
      });

      it('should set aria-valuetext', async () => {
        render(
          <SliderField defaultValue={0} label="slider" ariaValueText="Monday" />
        );
        const thumb = await screen.findByRole('slider');
        expect(thumb).toHaveAttribute('aria-valuetext', 'Monday');
      });
    });
  });

  describe('Error messages', () => {
    const errorMessage = 'This is an error message';
    it('should not show when hasError is false', async () => {
      render(
        <SliderField
          defaultValue={0}
          label="slider"
          errorMessage={errorMessage}
        />
      );

      const errorText = await screen.queryByText(errorMessage);
      expect(errorText).not.toBeInTheDocument();
    });

    it('show when hasError and errorMessage', async () => {
      render(
        <SliderField
          defaultValue={0}
          label="slider"
          errorMessage={errorMessage}
          hasError
        />
      );
      const errorText = await screen.queryByText(errorMessage);
      expect(errorText.innerHTML).toContain(errorMessage);
    });
  });

  describe('descriptive message', () => {
    it('should render descriptiveText if it is provided', async () => {
      render(
        <SliderField
          defaultValue={0}
          label="slider"
          descriptiveText="Description"
        />
      );

      const descriptiveText = await screen.queryByText('Description');
      expect(descriptiveText.innerHTML).toContain('Description');
    });
  });
});
