export enum LivenessClassNames {
  CameraModule = 'amplify-liveness-camera-module',
  CameraModuleCenteredLoader = 'amplify-liveness-camera-module__centered-loader',
  CameraModuleCanvas = 'amplify-liveness-camera-module__canvas',
  CameraModuleVideo = 'amplify-liveness-camera-module__video',

  CameraModuleRecordingIconContainer = 'amplify-liveness-camera-module__recording-icon-container',
  CameraModuleCancelButtonContainer = 'amplify-liveness-camera-module__cancel-button-container',
  CameraModuleOverlayCountdown = 'amplify-liveness-camera-module__overlay--countdown',
  CameraModuleCountdownTimerContainer = 'amplify-liveness-camera-module__countdown-timer-container',
  CancelButton = 'amplify-liveness__cancel-button',
  DescriptionBullet = 'amplify-liveness-description-bullet',
  DescriptionBulletIndexContainer = 'amplify-liveness-description-bullet__index-container',
  DescriptionBulletIndex = 'amplify-liveness-description-bullet__index',
  DescriptionBulletMessageContainer = 'amplify-liveness-description-bullet__message-container',
  DescriptionBulletMessageTitle = 'amplify-liveness-description-bullet__message--title',
  DescriptionBulletMessageBody = 'amplify-liveness-description-bullet__message--body',
  FadeOut = 'amplify-liveness-fade-out',
  OvalCanvas = 'amplify-liveness-oval-canvas',
  RecordingIcon = 'amplify-liveness__recording-icon',
  VideoContainer = 'amplify-liveness-video-container',
}
