// Jest doesn't support `exports` maps, so we have to reference `dist` directly.
// See: https://github.com/facebook/jest/issues/9771
import * as exported from '../dist';
import * as legacy from '../dist/legacy';

describe('@aws-amplify/ui-react', () => {
  describe('exports', () => {
    it('should match snapshot', () => {
      expect(Object.keys(exported)).toMatchInlineSnapshot(`
        Array [
          "Alert",
          "AmplifyProvider",
          "Authenticator",
          "Badge",
          "Box",
          "Button",
          "ButtonGroup",
          "Card",
          "CheckboxField",
          "Collection",
          "ComponentClassNames",
          "ComponentPropsToStylePropsMap",
          "ComponentPropsToStylePropsMapKeys",
          "Divider",
          "ErrorText",
          "Expander",
          "ExpanderItem",
          "FieldGroup",
          "FieldGroupIcon",
          "FieldGroupIconButton",
          "Fieldset",
          "Flex",
          "Footer",
          "Form",
          "Grid",
          "Header",
          "Heading",
          "Icon",
          "IconAdd",
          "IconCheck",
          "IconCheckCircle",
          "IconChevronLeft",
          "IconChevronRight",
          "IconClose",
          "IconCopy",
          "IconDarkMode",
          "IconDelete",
          "IconEmail",
          "IconError",
          "IconExpandMore",
          "IconExternalLink",
          "IconFavorite",
          "IconFavoriteOutline",
          "IconInfo",
          "IconLightMode",
          "IconMenu",
          "IconRemove",
          "IconSave",
          "IconSearch",
          "IconShare",
          "IconStar",
          "IconStarOutline",
          "IconVisibility",
          "IconVisibilityOff",
          "IconWarning",
          "Image",
          "Input",
          "Label",
          "Link",
          "Loader",
          "Main",
          "Menu",
          "MenuButton",
          "MenuItem",
          "Pagination",
          "PasswordField",
          "PhoneNumberField",
          "Placeholder",
          "Radio",
          "RadioGroupField",
          "Rating",
          "ScrollView",
          "SearchField",
          "SelectField",
          "SharedText",
          "SliderField",
          "Spacer",
          "StepperField",
          "SwitchField",
          "TabItem",
          "Tabs",
          "Text",
          "TextField",
          "ToggleButton",
          "ToggleButtonGroup",
          "View",
          "VisuallyHidden",
          "Wrapper",
          "components",
          "createDataStorePredicate",
          "createTheme",
          "defaultTheme",
          "findChildOverrides",
          "getOverrideProps",
          "getOverridesFromVariants",
          "primitives",
          "useAmplify",
          "useAuth",
          "useAuthenticator",
          "useDataStoreBinding",
          "useDataStoreCollection",
          "useDataStoreItem",
          "usePagination",
          "useStorageURL",
          "useTheme",
          "withAuthenticator",
        ]
      `);
    });
  });
});

describe('@aws-amplify/ui-react/legacy', () => {
  describe('exports', () => {
    it('should match snapshot', () => {
      expect(Object.keys(legacy)).toMatchInlineSnapshot(`
        Array [
          "AmplifyAuthenticator",
          "AmplifyChatbot",
          "AmplifyPhotoPicker",
          "AmplifyPicker",
          "AmplifyS3Album",
          "AmplifyS3Image",
          "AmplifyS3ImagePicker",
          "AmplifyS3Text",
          "AmplifyS3TextPicker",
          "AmplifySignIn",
          "AmplifySignOut",
          "withAuthenticator",
        ]
      `);
    });
  });
});
