export { default as SignIn } from './sign-in.vue';
export { default as SignUp } from './sign-up.vue';
export { default as Authenticator } from './authenticator.vue';
export { default as RenderInfo } from './primitives/render-info.vue';
export { default as SignUpEmailControl } from './sign-up-email-control.vue';
export { default as SignUpPasswordControl } from './sign-up-password-control.vue';
export { default as SignInPasswordControl } from './sign-in-password-control.vue';
export { default as SignUpPhoneControl } from './sign-up-phone-control.vue';
export { default as SignInAndUpNameControl } from './sign-in-and-up-name-control.vue';
