module.exports = {
  components: require('./components'),
  borderWidths: require('./borderWidths'),
  breakpoints: require('./breakpoints'),
  colors: require('./colors'),
  fonts: require('./fonts'),
  fontSizes: require('./fontSizes'),
  fontWeights: require('./fontWeights'),
  lineHeights: require('./lineHeights'),
  opacities: require('./opacities'),
  outlineOffsets: require('./outlineOffsets'),
  outlineWidths: require('./outlineWidths'),
  radii: require('./radii'),
  shadows: require('./shadows'),
  space: require('./space'),
  time: require('./time'),
};
