export * from './Badge';
export * from './Button';
export * from './Card';
export * from './Collection';
export * from './Divider';
export * from './Flex';
export * from './Heading';
export * from './Icon';
export * from './Image';
export * from './Pagination';
export * from './Placeholder';
export * from './Rating';
export * from './Text';
export * from './View';
export * from './shared';
export * from './types';
export declare function Box(props: any): JSX.Element;
export declare function Fieldset(props: any): JSX.Element;
export declare function Footer(props: any): JSX.Element;
export declare function Main(props: any): JSX.Element;
export declare function Form(props: any): JSX.Element;
export declare function Header(props: any): JSX.Element;
export declare function Input(props: any): JSX.Element;
export declare function Label(props: any): JSX.Element;
export declare function Spacer(props: any): JSX.Element;
export declare function ErrorText(props: any): JSX.Element;
export declare function Wrapper(props: any): JSX.Element;
