export enum ComponentClassNames {
  Badge = 'amplify-badge',
  Button = 'amplify-button',
  Card = 'amplify-card',
  Divider = 'amplify-divider',
  Flex = 'amplify-flex',
  Heading = 'amplify-heading',
  Icon = 'amplify-icon',
  Image = 'amplify-image',
  Pagination = 'amplify-pagination',
  Placeholder = 'amplify-placeholder',
  Rating = 'amplify-rating',
  Text = 'amplify-text',
  TextField = 'amplify-textfield',
  TextFieldInput = 'amplify-textfield__input',
  FieldWrapper = 'amplify-textfield-wrapper',
  TextFieldLabel = 'amplify-textfield__label',
  FieldDescription = 'amplify-field__description',
  FieldErrorMessage = 'amplify-field__error-message',
  View = 'amplify-view',
}
