export enum ComponentClassNames {
  Alert = 'amplify-alert',
  AlertHeading = 'amplify-alert-heading',
  Badge = 'amplify-badge',
  Button = 'amplify-button',
  Card = 'amplify-card',
  Divider = 'amplify-divider',
  Flex = 'amplify-flex',
  Heading = 'amplify-heading',
  Icon = 'amplify-icon',
  Image = 'amplify-image',
  Pagination = 'amplify-pagination',
  Placeholder = 'amplify-placeholder',
  Rating = 'amplify-rating',
  Tabs = 'amplify-tabs',
  TabList = 'amplify-tab-list',
  Text = 'amplify-text',
  View = 'amplify-view',
}
