import type { Metadata } from 'next';
import { Theme } from '@aws-amplify/ui-react/theme';
import { theme } from '@/theme';
import '@aws-amplify/ui-react/styles.css';
import { Avatar } from '@/components/Avatar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex w-full flex-row">
      <div className="flex-1 p-2">
        <h2>With custom theme</h2>

        <Theme.Style theme={theme} />
        <Theme.Container theme={theme} colorMode="system">
          <div>{children}</div>
          <Avatar size="small" />
          <Avatar />
          <Avatar size="large" />
        </Theme.Container>
      </div>
      <div className="flex-1 p-2">
        <h2>default theme</h2>
        {children}
      </div>
    </div>
  );
}
