export const PAINTINGS = [
  {
    title: 'Hallway',
    artist: 'Efe Kurnaz',
    src: 'https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Volutpat sed cras ornare arcu dui. Ac feugiat sed lectus vestibulum.',
    price: '$899.99',
    avgRating: 4.8,
    reviews: 445,
    inStock: true,
    readyForPickup: true,
    bestSeller: true,
    isNew: false,
    limitedSupply: false,
  },
  {
    title: 'Fire and Ice',
    artist: 'Pawel Czerwinski',
    src: 'https://images.unsplash.com/photo-1604871000636-074fa5117945?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987',
    description:
      'Lorem ipsum dolor sit amet, ubique patrioque at qui, modo hinc ne duo, ad consul animal volumus est. Ea quo etiam deleniti, amet singulis in sed. Omnesque lobortis vis ex. Wisi latine splendide vis ei, libris commodo no has.',
    price: '$699.99',
    avgRating: 4.1,
    reviews: 222,
    inStock: true,
    readyForPickup: true,
    bestSeller: false,
    isNew: false,
    limitedSupply: false,
  },
  {
    title: 'Orange, pink, yellow',
    artist: 'Kseniya Lapteva',
    src: 'https://images.unsplash.com/photo-1629196914375-f7e48f477b6d?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1306',
    description:
      'Lorem ipsum dolor sit amet, cu porro vivendum ius. Ad mei sint homero, cum an soluta epicurei. At pri minimum corrumpit. Minim percipitur eu mei, erant habemus deserunt qui et.',
    price: '$139.99',
    avgRating: 3.5,
    reviews: 142,
    inStock: true,
    readyForPickup: false,
    bestSeller: false,
    isNew: true,
    limitedSupply: false,
  },
  {
    title: 'Melted Purple',
    artist: 'Maria Orlova',
    src: 'https://images.unsplash.com/photo-1549490349-8643362247b5?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987',
    description:
      'Lorem ipsum dolor sit amet, facer nemore ei sea, mea facilis eloquentiam at. Et modus pertinax tincidunt est. Propriae argumentum necessitatibus eos ad.',
    price: '$499.99',
    avgRating: 4.5,
    reviews: 301,
    inStock: true,
    readyForPickup: true,
    bestSeller: true,
    isNew: false,
    limitedSupply: false,
  },
  {
    title: 'Experimental',
    artist: 'Bruno Thethe',
    src: 'https://images.unsplash.com/photo-1550275994-cdc89cd1948f?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987',
    description:
      'Lorem ipsum dolor sit amet, ea probo choro tollit pri, ad pro justo intellegam repudiandae, labores civibus eu quo. Cum latine instructior at, est no odio tibique epicuri.',
    price: '$159.99',
    avgRating: 3.1,
    reviews: 56,
    inStock: true,
    readyForPickup: true,
    bestSeller: false,
    isNew: true,
    limitedSupply: false,
  },
  {
    title: 'Rainbow',
    artist: 'Felix Spiske',
    src: 'https://images.unsplash.com/photo-1543857778-c4a1a3e0b2eb?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1310',
    description:
      'Lorem ipsum dolor sit amet, sea tritani indoctum cu, facilis praesent at qui. Cu cetero veritus vel, et prima erant perfecto vix. Tollit delectus scaevola duo et, inermis sensibus voluptatum cu ius.',
    price: '$799.99',
    avgRating: 4.9,
    reviews: 550,
    inStock: true,
    readyForPickup: false,
    bestSeller: true,
    isNew: false,
    limitedSupply: true,
  },
  {
    title: 'Fearless Hue',
    artist: 'Radienta',
    src: 'https://images.unsplash.com/photo-1579547621113-e4bb2a19bdd6?ixlib=rb-1.2.1&raw_url=true&q=80&fm=jpg&crop=entropy&cs=tinysrgb&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=939',
    description:
      'Lorem ipsum dolor sit amet, te labore lucilius pro, te his consul singulis, cu vel unum impedit complectitur. In usu erat dicta doctus, purto aeterno vis te. Facete deterruisset nec id. At omittam antiopam pri.',
    price: '$249.99',
    avgRating: 3.3,
    reviews: 294,
    inStock: true,
    readyForPickup: true,
    bestSeller: false,
    isNew: false,
    limitedSupply: false,
  },
  {
    title: 'Liquid',
    artist: 'Joel Filipe',
    src: 'https://images.unsplash.com/photo-1485163819542-13adeb5e0068?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987',
    description:
      'Lorem ipsum dolor sit amet, cum cu meliore tacimates, vel no sale maiorum. His cu autem placerat. Homero urbanitas vituperata ad sit, ex mel convenire elaboraret.',
    price: '$549.99',
    avgRating: 4.5,
    reviews: 440,
    inStock: false,
    readyForPickup: false,
    bestSeller: false,
    isNew: false,
    limitedSupply: true,
  },
];
