/**
 * The liveness error states
 */

export enum LivenessErrorState {
  TIMEOUT = 'TIMEOUT',
  RUNTIME_ERROR = 'RUNTIME_ERROR',
  FRESHNESS_TIMEOUT = 'FRESHNESS_TIMEOUT',
  SERVER_ERROR = 'SERVER_ERROR',
  CAMERA_FRAMERATE_ERROR = 'CAMERA_FRAMERATE_ERROR',
  CAMERA_ACCESS_ERROR = 'CAMERA_ACCESS_ERROR',
  FACE_DISTANCE_ERROR = 'FACE_DISTANCE_ERROR',
  MOBILE_LANDSCAPE_ERROR = 'MOBILE_LANDSCAPE_ERROR',
  MULTIPLE_FACES_ERROR = 'MULTIPLE_FACES_ERROR',
}

export type ErrorState =
  | LivenessErrorState.TIMEOUT
  | LivenessErrorState.RUNTIME_ERROR
  | LivenessErrorState.FRESHNESS_TIMEOUT
  | LivenessErrorState.SERVER_ERROR
  | LivenessErrorState.CAMERA_FRAMERATE_ERROR
  | LivenessErrorState.CAMERA_ACCESS_ERROR
  | LivenessErrorState.FACE_DISTANCE_ERROR
  | LivenessErrorState.MOBILE_LANDSCAPE_ERROR
  | LivenessErrorState.MULTIPLE_FACES_ERROR;
