#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

yarn install
yarn build

# React's build doesn't pick up on patch changes, so we need to run it twice
yarn patch-package
yarn react build
