#!/bin/sh
branch="$(git branch --show-current)"

if [ "$branch" = "main" ]; then
  echo "Direct commits to main branch are not allowed."
  exit 1
fi

. "$(dirname "$0")/_/husky.sh"

echo "Scanning committed files for secrets..."
git secrets --pre_commit_hook -- "$@"

npx lint-staged
