#!/bin/sh
branch="$(git branch --show-current)"

if [ "$branch" = "main" ]; then
  echo "Direct commits to main branch are not allowed."
  exit 1
fi

. "$(dirname "$0")/_/husky.sh"

# Check git-secrets installation
if ! command -v git-secrets &> /dev/null
then
    echo "git-secrets is not installed. Please run 'brew install git-secrets' or visit https://github.com/awslabs/git-secrets#installing-git-secrets"
    exit 1
fi

# Initialize git-secrets configuration
git secrets --register-aws > /dev/null
# git config --unset providers
git_secrets_output="$(git secrets --list)"
echo $git_secrets_output
# git secrets --add-provider -- cat .husky/.secret.patterns
# git secrets --add 'smil\.mil'
# git secrets --add '(us|aws)-iso'
# git secrets --add '[aA]pollo|[bB]razil|[cC]oral|[oO]din'
# git secrets --add 'tt\.amazon\.com|issues\.amazon\.com|cr\.amazon\.com'
# git secrets --add 'ic\.gov|sgov\.gov'
# git secrets --add '(us|aws)-iso'

echo "Scanning committed files for secrets..."
git secrets --pre_commit_hook -- "$@"

# npx lint-staged
