#!/bin/sh
while read local_ref local_sha remote_ref remote_sha; do
  # Check if the local branch name starts with "docs-release-pr", in which case exit successfully
  if [[ "$local_ref" =~ ^refs/heads/docs-release-pr-.* ]]; then
    exit 0
  fi
  
  # Get the list of changed files in this commit
  changed_files="$(git diff --name-only "${local_sha}" "${remote_sha}")"

  # Check if any of the changed files are in the angular, react, react-native, ui or vue packages
  if echo "${changed_files}" | grep -E '^packages/angular/|^packages/react/|^packages/react-core/|^packages/react-native/|^packages/ui/|^packages/vue/'; then
    # Check if a changeset file is present and has .md extension
    if echo "${changed_files}" | grep -E '^\.changeset/.*\.md$'; then
      exit 0
    else
      echo "ERROR: These changes should result in a version bump but no changeset was found! \nPlease add a changeset file by running yarn changeset."
      exit 1
    fi
  fi
done

exit 0
