#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check git-secrets installation
if ! command -v git-secrets &> /dev/null
then
    echo "git-secrets is not installed. Please run 'brew install git-secrets' or visit https://github.com/awslabs/git-secrets#installing-git-secrets"
    exit 1
fi

# Initialize git-secrets configuration
git secrets --register-aws > /dev/null

echo "Scanning commit history for secrets..."
# Determines if merging in a commit will introduce tainted history.
git secrets --prepare_commit_msg_hook -- "$@"
