#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Scanning commit history for secrets..."
# Determines if merging in a commit will introduce tainted history.
git secrets --prepare_commit_msg_hook -- "$@"
