import 'jest-canvas-mock';
import {
  clearOvalCanvas,
  drawLivenessOvalInCanvas,
  drawStaticOval,
  estimateIllumination,
  fillOverlayCanvasFractional,
  generateBboxFromLandmarks,
  getColorsSequencesFromSessionInformation,
  getFaceMatchState,
  getOvalBoundingBox,
  getOvalDetailsFromSessionInformation,
  getStaticLivenessOvalDetails,
  getVideoFillLayout,
  getVideoScaleFactor,
  isCameraDeviceVirtual,
  isFaceDistanceBelowThreshold,
  resizeCanvasToDisplaySize,
} from '../liveness';
import {
  getMockContext,
  mockCameraDevice,
  mockFace,
  mockOvalDetails,
  mockFaceMovementAndLightSessionInfo,
} from '../__mocks__/testUtils';
import {
  Face,
  FaceMatchState,
  FaceMovementAndLightChallenge,
  IlluminationState,
  LivenessErrorState,
} from '../../types';

const context = getMockContext();

const MOCK_TIMESTAMP = 1640995200000;

// Values generated by passing mockFace into generateBboxFromLandmarks and printing intermediate values
const mockFaceHeight = 0; // 1.68 * [(ALPHA * pd + GAMMA * fh) / 2];
const mockFaceCenterY = 200; // eyeCenter[1];

const mockAboveFrameFace: Face = {
  height: 215,
  left: 200,
  leftEar: [420, 155],
  leftEye: [360, 110],
  mouth: [310, 200],
  nose: [310, 140],
  probability: 90,
  rightEar: [215, 170],
  rightEye: [260, 115],
  timestampMs: MOCK_TIMESTAMP,
  top: 70,
  width: 215,
};

const mockCloselyMatchedFace: Face = {
  top: 46.751117706298814,
  left: -5.630989074707031,
  width: 572.6491546630859,
  height: 572.7001762390136,
  timestampMs: MOCK_TIMESTAMP,
  probability: 90,
  rightEye: [187.4885559082032, 218.63224029541013],
  leftEye: [433.75030517578125, 227.35191345214847],
  mouth: [313.39622497558594, 485.65040588378895],
  nose: [330.15281677246094, 371.40689849853516],
  rightEar: [28.786602020263672, 237.78337478637698],
  leftEar: [515.0150299072266, 262.62935638427734],
};

const mockMatchedFace: Face = {
  height: 317.5821685791015,
  left: 165.49339294433594,
  leftEar: [445, 264.4227600097656],
  leftEye: [384.70985412597656, 247.56172180175784],
  mouth: [327.9991149902344, 393.5927200317383],
  nose: [325.2409362792969, 333.89575958251953],
  probability: 90,
  rightEar: [199.34513092041016, 272.49412536621094],
  rightEye: [261.6714286804199, 250.6684875488281],
  timestampMs: MOCK_TIMESTAMP,
  top: 155.82656860351565,
  width: 317.60498046875,
};
const mockMatchedFaceCenterX = 323.19064140319824;
const mockMatchedFaceOcularWidth = 253.17949214956178;

const mockTurnedFace: Face = {
  height: 215.05796432495114,
  left: 235.08899688720703,
  leftEar: [433.8389587402344, 233.52020263671872],
  leftEye: [379.2174530029297, 205.73320388793942],
  mouth: [340.50960540771484, 304.9227523803711],
  nose: [337.0632553100586, 257.2260284423828],
  probability: 90,
  rightEar: [250.12165069580078, 249.12113189697263],
  rightEye: [292.9753875732422, 215.29994964599607],
  timestampMs: MOCK_TIMESTAMP,
  top: 158.50336074829102,
  width: 215.0579833984375,
};

describe('Liveness Helper', () => {
  describe('getOvalDetailsFromSessionInformation', () => {
    it('should parse parsedSessionInformation and return oval parameter attributes', () => {
      const ovalParameters = getOvalDetailsFromSessionInformation({
        parsedSessionInformation: mockFaceMovementAndLightSessionInfo,
        videoWidth: 1,
      });

      expect(ovalParameters.centerX).toBe(3);
      expect(ovalParameters.centerY).toBe(4);
      expect(ovalParameters.width).toBe(1);
      expect(ovalParameters.height).toBe(2);
    });

    it('should throw an error if some oval parameters are not defined', () => {
      const badSessionInfo = {
        ...mockFaceMovementAndLightSessionInfo,
        Challenge: {
          ...mockFaceMovementAndLightSessionInfo.Challenge,
          OvalParameters: {
            Width: undefined,
            Height: undefined,
            CenterX: undefined,
            CenterY: undefined,
          },
        } as FaceMovementAndLightChallenge,
      };

      expect(() => {
        getOvalDetailsFromSessionInformation({
          parsedSessionInformation: badSessionInfo,
          videoWidth: 1,
        });
      }).toThrow();
    });
  });

  describe('getFaceMatchState', () => {
    const mockBlazeFace: any = {
      modelLoadingPromise: Promise.resolve(),
      triggerModelLoading: jest.fn(),
      loadModels: jest.fn(),
      detectFaces: jest.fn(),
    };
    it('should return FACE_IDENTIFIED if only one face returned', async () => {
      mockBlazeFace.detectFaces.mockResolvedValue([mockFace]);

      const faceMatchState = await getFaceMatchState(
        mockBlazeFace,
        jest.fn() as unknown as HTMLVideoElement
      );

      expect(faceMatchState).toBe(FaceMatchState.FACE_IDENTIFIED);
    });

    it('should return CANT_IDENTIFY if no faces returned', async () => {
      mockBlazeFace.detectFaces.mockResolvedValue([]);

      const faceMatchState = await getFaceMatchState(
        mockBlazeFace,
        jest.fn() as unknown as HTMLVideoElement
      );

      expect(faceMatchState).toBe(FaceMatchState.CANT_IDENTIFY);
    });

    it('should return TOO_MANY if more than one face returned', async () => {
      mockBlazeFace.detectFaces.mockResolvedValue([mockFace, mockFace]);

      const faceMatchState = await getFaceMatchState(
        mockBlazeFace,
        jest.fn() as unknown as HTMLVideoElement
      );

      expect(faceMatchState).toBe(FaceMatchState.TOO_MANY);
    });
  });

  describe('generateBboxfromLandmarks', () => {
    it(`should return face box bottom as 'bottom' when face is within frame`, () => {
      const frameHeight = 480;
      const { bottom } = generateBboxFromLandmarks({
        face: mockFace,
        oval: mockOvalDetails,
        frameHeight: frameHeight,
        ovalHeightWidthRatio: 1.6180000305175781,
      });

      const faceBoxBottom = mockFaceCenterY + mockFaceHeight / 2;
      expect(bottom).toEqual(faceBoxBottom); // expect calculated value to be returned as it is within frame
    });

    it(`should return 'frameHeight' as 'bottom' when bottom of face is below frame`, () => {
      const frameHeight = 100;
      const { bottom } = generateBboxFromLandmarks({
        face: mockFace,
        oval: mockOvalDetails,
        frameHeight: frameHeight,
        ovalHeightWidthRatio: 1.6180000305175781,
      });
      expect(bottom).toEqual(frameHeight); // expect frameHeight to be returned as it is smaller than the calculated value
    });

    it(`should return face box top as 'top' when face is within frame`, () => {
      const frameHeight = 480;
      const { top } = generateBboxFromLandmarks({
        face: mockFace,
        oval: mockOvalDetails,
        frameHeight: frameHeight,
        ovalHeightWidthRatio: 1.6180000305175781,
      });

      const faceBoxTop = mockFaceCenterY - mockFaceHeight / 2;

      expect(top).toEqual(faceBoxTop);
    });

    it(`should return 0 as 'top' when top of face is above frame`, () => {
      const frameHeight = 480;
      const { top } = generateBboxFromLandmarks({
        face: mockAboveFrameFace,
        oval: mockOvalDetails,
        frameHeight: frameHeight,
        ovalHeightWidthRatio: 1.6180000305175781,
      });

      expect(top).toEqual(0);
    });

    it(`should return correct 'left' and 'right' values when face is matched`, () => {
      const frameHeight = 480;

      const { left, right } = generateBboxFromLandmarks({
        face: mockMatchedFace,
        oval: mockOvalDetails,
        frameHeight: frameHeight,
        ovalHeightWidthRatio: 1.6180000305175781,
      });

      const faceBoxRight =
        mockMatchedFaceCenterX + mockMatchedFaceOcularWidth / 2;
      const faceBoxLeft =
        mockMatchedFaceCenterX - mockMatchedFaceOcularWidth / 2;
      expect(left).toEqual(faceBoxLeft); // expect left = cx - ow / 2
      expect(right).toEqual(faceBoxRight); // expect right = cx + ow / 2
    });

    it(`should return correct 'left' and 'right' values when face is turned`, () => {
      const frameHeight = 480;
      const { left, right } = generateBboxFromLandmarks({
        face: mockTurnedFace,
        oval: mockOvalDetails,
        frameHeight: frameHeight,
        ovalHeightWidthRatio: 1.6180000305175781,
      });

      expect(left).toEqual(mockTurnedFace.rightEar[0]); // expect right ear to be used to limit left edge of face
      expect(right).toEqual(mockTurnedFace.leftEar[0]); // expect left ear to be used to limit right edge of face
    });
  });

  describe('isFaceDistanceBelowThreshold', () => {
    const mockBlazeFace: any = {
      modelLoadingPromise: Promise.resolve(),
      triggerModelLoading: jest.fn(),
      loadModels: jest.fn(),
      detectFaces: jest.fn(),
    };
    it('should return false if no faces', async () => {
      mockBlazeFace.detectFaces.mockResolvedValue([]);

      const result = await isFaceDistanceBelowThreshold({
        faceDetector: mockBlazeFace,
        videoEl: jest.fn() as unknown as HTMLVideoElement,
        ovalDetails: mockOvalDetails,
        parsedSessionInformation: mockFaceMovementAndLightSessionInfo,
      });

      expect(result).toStrictEqual({
        error: 'FACE_DISTANCE_ERROR',
        isDistanceBelowThreshold: false,
      });
    });

    it('should return false if more than one face', async () => {
      mockBlazeFace.detectFaces.mockResolvedValue([mockFace, mockFace]);

      const result = await isFaceDistanceBelowThreshold({
        faceDetector: mockBlazeFace,
        videoEl: jest.fn() as unknown as HTMLVideoElement,
        ovalDetails: mockOvalDetails,
        parsedSessionInformation: mockFaceMovementAndLightSessionInfo,
      });

      expect(result).toStrictEqual({
        error: 'MULTIPLE_FACES_ERROR',
        isDistanceBelowThreshold: false,
      });
    });

    it('should return true if below threshold', async () => {
      mockBlazeFace.detectFaces.mockResolvedValue([mockFace]);

      const result = await isFaceDistanceBelowThreshold({
        faceDetector: mockBlazeFace,
        videoEl: jest.fn() as unknown as HTMLVideoElement,
        ovalDetails: mockOvalDetails,
        reduceThreshold: true,
        parsedSessionInformation: mockFaceMovementAndLightSessionInfo,
      });

      expect(result).toStrictEqual({
        error: undefined,
        isDistanceBelowThreshold: true,
      });
    });

    it('should return false and error if above threshold', async () => {
      mockBlazeFace.detectFaces.mockResolvedValue([mockCloselyMatchedFace]);

      const result = await isFaceDistanceBelowThreshold({
        faceDetector: mockBlazeFace,
        videoEl: jest.fn() as unknown as HTMLVideoElement,
        ovalDetails: mockOvalDetails,
        reduceThreshold: true,
        parsedSessionInformation: mockFaceMovementAndLightSessionInfo,
      });

      expect(result).toStrictEqual({
        error: LivenessErrorState.FACE_DISTANCE_ERROR,
        isDistanceBelowThreshold: false,
      });
    });
  });

  describe('getColorsSequencesFromSessionInformation', () => {
    it('should return a parsed color sequence', async () => {
      const colorSequence = getColorsSequencesFromSessionInformation(
        mockFaceMovementAndLightSessionInfo
      );

      expect(colorSequence.length).toBe(8);
      expect(colorSequence[0]).toStrictEqual({
        color: 'rgb(0,0,0)',
        downscrollDuration: 300,
        flatDisplayDuration: 100,
      });
    });

    it('should work even if there are no color sequences', async () => {
      const colorSequence = getColorsSequencesFromSessionInformation({
        ...mockFaceMovementAndLightSessionInfo,
        Challenge: {
          ...mockFaceMovementAndLightSessionInfo.Challenge,
          ColorSequences: undefined,
        } as FaceMovementAndLightChallenge,
      });

      expect(colorSequence.length).toBe(0);
    });

    it('should not return values if color sequences do not contain durations', async () => {
      const mockMissingDurationSessionInfo = {
        ...mockFaceMovementAndLightSessionInfo,
        Challenge: {
          ...mockFaceMovementAndLightSessionInfo.Challenge,
          ColorSequences: [
            {
              FreshnessColor: {
                RGB: [0, 0, 0], // black
              },
              DownscrollDuration: undefined,
              FlatDisplayDuration: undefined,
            },
          ],
        } as FaceMovementAndLightChallenge,
      };

      const colorSequence = getColorsSequencesFromSessionInformation(
        mockMissingDurationSessionInfo
      );

      expect(colorSequence.length).toBe(0);
    });
  });

  describe('isCameraDeviceVirtual', () => {
    it('should return true if device is virtual', () => {
      const device = {
        ...mockCameraDevice,
        label: 'ManyCam Virtual Webcam',
      };

      expect(isCameraDeviceVirtual(device)).toBe(true);
    });

    it('should return false if device is not virtual', () => {
      const device = {
        ...mockCameraDevice,
        label: 'FaceTime HD Camera (Built-in)',
      };

      expect(isCameraDeviceVirtual(device)).toBe(false);
    });
  });

  describe('drawLivenessOvalInCanvas', () => {
    it('should call canvas functions for drawing the provided oval', () => {
      const canvas = context.videoAssociatedParams?.canvasEl!;
      const oval = mockOvalDetails;
      const scaleFactor = 1;
      const videoEl = context.videoAssociatedParams?.videoEl!;
      drawLivenessOvalInCanvas({
        canvas,
        oval,
        scaleFactor,
        videoEl,
      });

      const canvasContext = canvas.getContext('2d');
      const drawCalls = (canvasContext as any).__getDrawCalls();
      const path = (canvasContext as any)._path;
      // Final call should be to clear the middle of the oval so we can see the face
      expect(drawCalls[drawCalls.length - 1].type).toBe('clearRect');
      expect(path[0].type).toBe('beginPath');
      expect(path[1].type).toBe('ellipse');
      expect(path[2].type).toBe('clip');
    });
  });

  describe('getVideoScaleFactor', () => {
    const createVideo = (rect: { width: number; height: number }) => {
      const videoEl = document.createElement('video');
      Object.defineProperty(videoEl, 'videoWidth', { value: 640 });
      Object.defineProperty(videoEl, 'videoHeight', { value: 480 });
      Object.defineProperty(videoEl, 'clientWidth', { value: rect.width });
      Object.defineProperty(videoEl, 'clientHeight', { value: rect.height });
      return videoEl;
    };

    it('should return the width ratio when the video box matches the frame', () => {
      expect(
        getVideoScaleFactor(createVideo({ width: 960, height: 720 }))
      ).toBe(1.5);
    });

    it('should use the height ratio when the frame is pillarboxed', () => {
      expect(
        getVideoScaleFactor(createVideo({ width: 960, height: 240 }))
      ).toBe(0.5);
    });

    it('should use the width ratio when the frame is letterboxed', () => {
      expect(
        getVideoScaleFactor(createVideo({ width: 320, height: 720 }))
      ).toBe(0.5);
    });

    it('should return 1 before video metadata is loaded', () => {
      const videoEl = document.createElement('video');
      expect(getVideoScaleFactor(videoEl)).toBe(1);
    });
  });

  describe('getVideoFillLayout', () => {
    const video = { videoWidth: 640, videoHeight: 480 };

    it('should match the container when it has the frame aspect ratio', () => {
      expect(
        getVideoFillLayout({
          containerWidth: 640,
          containerHeight: 480,
          ...video,
        })
      ).toEqual({ width: 640, height: 480, left: 0, top: 0 });
    });

    it('should fit the height and pillarbox in a wide container', () => {
      expect(
        getVideoFillLayout({
          containerWidth: 1000,
          containerHeight: 480,
          ...video,
        })
      ).toEqual({ width: 640, height: 480, left: 180, top: 0 });
    });

    it('should fill the height of a tall container by cropping the sides', () => {
      // 640x600 container: fill height => frame 800 wide, 80% visible
      expect(
        getVideoFillLayout({
          containerWidth: 640,
          containerHeight: 600,
          ...video,
        })
      ).toEqual({ width: 800, height: 600, left: -80, top: 0 });
    });

    it('should never crop more than the allowed fraction of the frame width', () => {
      const { width, height, top } = getVideoFillLayout({
        containerWidth: 448,
        containerHeight: 2000,
        ...video,
      });
      // 448 / 0.7 = 640 => at most 30% of the frame width is cropped
      expect(width).toBeCloseTo(640);
      expect(height).toBeCloseTo(480);
      expect(top).toBeCloseTo(760);
    });
  });

  // T2.2: the 3:4 recompute in getStaticLivenessOvalDetails is the branch
  // desktop landscape has always taken (640 >= 480). Mobile landscape and
  // square foldable frames must take the identical branch, so the distance
  // check behaves the same everywhere rather than gaining a mobile-only path.
  describe('getStaticLivenessOvalDetails dimension matrix', () => {
    const portrait = { width: 480, height: 640 };
    const landscape = { width: 640, height: 480 };
    const square = { width: 480, height: 480 };

    it.each([
      ['desktop landscape', landscape],
      ['mobile landscape', landscape],
      ['square foldable', square],
    ])('should take the 3:4 branch for %s', (_label, dims) => {
      const oval = getStaticLivenessOvalDetails(dims);

      // videoWidth is recomputed as (3/4) * height, so the oval width is
      // ratioMultiplier * that, independent of the real frame width
      expect(oval.width).toBe(Math.floor(0.8 * (3 / 4) * dims.height));
    });

    it('should keep the true frame width in portrait', () => {
      const oval = getStaticLivenessOvalDetails(portrait);

      expect(oval.width).toBe(Math.floor(0.8 * portrait.width));
    });

    it('should produce an identical oval for desktop and mobile landscape', () => {
      // same dims in, same oval out: there is no device branch to diverge on
      expect(getStaticLivenessOvalDetails(landscape)).toEqual(
        getStaticLivenessOvalDetails(landscape)
      );
    });

    it.each([
      ['portrait', portrait],
      ['landscape', landscape],
      ['square', square],
    ])('should keep the oval bounding box inside the %s frame', (_l, dims) => {
      const oval = getStaticLivenessOvalDetails(dims);
      const { minOvalX, maxOvalX, minOvalY, maxOvalY } =
        getOvalBoundingBox(oval);

      expect(minOvalX).toBeGreaterThanOrEqual(0);
      expect(maxOvalX).toBeLessThanOrEqual(dims.width);
      expect(minOvalY).toBeGreaterThanOrEqual(0);
      expect(maxOvalY).toBeLessThanOrEqual(dims.height);
    });
  });

  // The supported landscape floor is 360 CSS px of container height.
  describe('landscape viewport floor', () => {
    const video = { videoWidth: 640, videoHeight: 480 };
    // the oval the challenge actually draws, in frame space
    const oval = getStaticLivenessOvalDetails({
      width: video.videoWidth,
      height: video.videoHeight,
      ratioMultiplier: 0.8,
    });

    it.each([
      [800, 360],
      [915, 412],
      [740, 360],
    ])('should fit the oval in a %ix%i viewport', (width, height) => {
      const layout = getVideoFillLayout({
        containerWidth: width,
        containerHeight: height,
        ...video,
      });
      const scale = layout.height / video.videoHeight;

      expect(oval.height * scale).toBeLessThanOrEqual(height);
    });

    it('should leave the oval under the frame height, so no clamp is needed', () => {
      // 465 of 480: the oval is height-bound in landscape and getVideoFillLayout
      // never scales the frame past the container height, so the rendered oval
      // cannot exceed this fraction of the container at any landscape size.
      expect(oval.height / video.videoHeight).toBeCloseTo(0.969, 3);
    });
  });

  describe('resizeCanvasToDisplaySize', () => {
    it('should size the canvas buffer to its parent box', () => {
      const parent = document.createElement('div');
      const canvas = document.createElement('canvas');
      parent.appendChild(canvas);
      Object.defineProperty(parent, 'clientWidth', { value: 800.4 });
      Object.defineProperty(parent, 'clientHeight', { value: 600.2 });

      resizeCanvasToDisplaySize(canvas);

      expect(canvas.width).toBe(801);
      expect(canvas.height).toBe(601);
    });
  });

  describe('drawStaticOval', () => {
    it('should center the oval in the intrinsic frame when the track dims are flipped', () => {
      // Android/Firefox and iOS report the getUserMedia width/height flipped by
      // orientation. The oval must follow the 640x480 frame the video element
      // actually renders, which puts its center in [280, 360] (7/16 to 9/16 of
      // 640). Sizing from a flipped 480-wide track would land in [120, 200].
      const parent = document.createElement('div');
      const canvasEl = document.createElement('canvas');
      parent.appendChild(canvasEl);
      Object.defineProperty(parent, 'clientWidth', { value: 800 });
      Object.defineProperty(parent, 'clientHeight', { value: 360 });

      const videoEl = document.createElement('video');
      Object.defineProperty(videoEl, 'videoWidth', { value: 640 });
      Object.defineProperty(videoEl, 'videoHeight', { value: 480 });
      Object.defineProperty(videoEl, 'clientWidth', { value: 480 });
      Object.defineProperty(videoEl, 'clientHeight', { value: 360 });

      drawStaticOval(canvasEl, videoEl);

      const path = (canvasEl.getContext('2d') as any)._path;
      const ellipse = path.find((entry: any) => entry.type === 'ellipse');
      expect(ellipse).toBeDefined();
      expect(ellipse.props.x).toBeGreaterThanOrEqual(280);
      expect(ellipse.props.x).toBeLessThanOrEqual(360);
      expect(ellipse.props.y).toBeGreaterThanOrEqual(210);
      expect(ellipse.props.y).toBeLessThanOrEqual(270);
    });
  });

  describe('fillOverlayCanvasFractional', () => {
    it('should position the oval correctly under a scale transform', () => {
      // an ancestor applies `transform: scale(0.5)`: rects are halved while
      // layout sizes (clientWidth/clientHeight) are not
      const overlayCanvas = document.createElement('canvas');
      Object.defineProperty(overlayCanvas, 'clientWidth', { value: 1000 });
      Object.defineProperty(overlayCanvas, 'clientHeight', { value: 800 });
      overlayCanvas.getBoundingClientRect = () =>
        ({ x: 100, y: 50, width: 500, height: 400 }) as DOMRect;
      const videoEl = document.createElement('video');
      Object.defineProperty(videoEl, 'videoWidth', { value: 640 });
      Object.defineProperty(videoEl, 'videoHeight', { value: 480 });
      Object.defineProperty(videoEl, 'clientWidth', { value: 840 });
      Object.defineProperty(videoEl, 'clientHeight', { value: 480 });
      // pillarboxed 640x480 frame at scale 1 inside an 840x480 layout box
      videoEl.getBoundingClientRect = () =>
        ({ x: 200, y: 100, width: 420, height: 240 }) as DOMRect;

      fillOverlayCanvasFractional({
        overlayCanvas,
        prevColor: 'red',
        nextColor: 'black',
        videoEl,
        ovalDetails: {
          ...mockOvalDetails,
          flippedCenterX: 320,
          centerY: 240,
          width: 200,
          height: 300,
        },
        heightFraction: 1,
        scaleFactor: 1,
      });

      // buffer uses the canvas layout size, not the transformed size
      expect(overlayCanvas.width).toBe(1000);
      expect(overlayCanvas.height).toBe(800);
      const ctx = overlayCanvas.getContext('2d') as any;
      const ellipse = ctx
        .__getEvents()
        .find((e: { type: string }) => e.type === 'ellipse');
      // video starts (200 - 100) / 0.5 = 200 into the canvas, + 100 pillarbox
      expect(ellipse.props.x).toBe(620);
      // video starts (100 - 50) / 0.5 = 100 into the canvas
      expect(ellipse.props.y).toBe(340);
      expect(ellipse.props.radiusX).toBe(100);
      expect(ellipse.props.radiusY).toBe(150);
    });

    it('should position the oval relative to the overlay canvas, not the viewport', () => {
      const overlayCanvas = document.createElement('canvas');
      // overlay is offset, as when a transformed modal ancestor contains it
      overlayCanvas.getBoundingClientRect = () =>
        ({ x: 100, y: 50, width: 1000, height: 800 }) as DOMRect;
      const videoEl = document.createElement('video');
      Object.defineProperty(videoEl, 'videoWidth', { value: 640 });
      Object.defineProperty(videoEl, 'videoHeight', { value: 480 });
      // pillarboxed 640x480 frame at scale 1 inside an 840x480 video box
      videoEl.getBoundingClientRect = () =>
        ({ x: 200, y: 100, width: 840, height: 480 }) as DOMRect;

      fillOverlayCanvasFractional({
        overlayCanvas,
        prevColor: 'red',
        nextColor: 'black',
        videoEl,
        ovalDetails: { ...mockOvalDetails, flippedCenterX: 320, centerY: 240 },
        heightFraction: 1,
        scaleFactor: 1,
      });

      expect(overlayCanvas.width).toBe(1000);
      expect(overlayCanvas.height).toBe(800);
      const ctx = overlayCanvas.getContext('2d') as any;
      const ellipse = ctx
        .__getEvents()
        .find((e: { type: string }) => e.type === 'ellipse');
      // frame origin = video x (200) + pillarbox (100) - canvas x (100)
      expect(ellipse.props.x).toBe(520);
      // frame origin = video y (100) - canvas y (50)
      expect(ellipse.props.y).toBe(290);
    });

    it('should fail if canvas context is undefined', () => {
      const mockGetContext = jest.fn().mockReturnValue(undefined);
      const canvas = context.videoAssociatedParams?.canvasEl!;
      (canvas as any).getContext = mockGetContext;
      const oval = mockOvalDetails;
      const scaleFactor = 1;
      const videoEl = context.videoAssociatedParams?.videoEl!;
      expect(() =>
        fillOverlayCanvasFractional({
          overlayCanvas: canvas,
          prevColor: 'red',
          nextColor: 'black',
          videoEl,
          ovalDetails: oval,
          heightFraction: 1,
          scaleFactor,
        })
      ).toThrow();
    });
  });

  describe('estimateIllumination', () => {
    it('should fail if canvas context is undefined', () => {
      const mockGetContext = jest.fn().mockReturnValue(undefined);
      const canvas = context.videoAssociatedParams?.canvasEl!;
      (canvas as any).getContext = mockGetContext;
      const videoEl = context.videoAssociatedParams?.videoEl!;
      expect(() => estimateIllumination(videoEl)).toThrow();
    });

    it('should return too dark on an empty video element ', () => {
      const videoEl = context.videoAssociatedParams?.videoEl!;
      Object.defineProperty(videoEl, 'videoWidth', { value: 100 });
      Object.defineProperty(videoEl, 'videoHeight', { value: 100 });
      expect(estimateIllumination(videoEl)).toBe(IlluminationState.DARK);
    });
  });

  describe('clearOvalCanvas', () => {
    it('should attempt to clear the oval canvas', () => {
      const canvas = getMockContext().videoAssociatedParams?.canvasEl!;

      clearOvalCanvas({ canvas });

      const canvasContext = canvas.getContext('2d');

      expect(canvasContext!.restore).toBeCalled();
      expect(canvasContext!.clearRect).toBeCalled();
    });

    it('should fail if no context is found', () => {
      const mockGetContext = jest.fn().mockReturnValue(undefined);
      const canvas = context.videoAssociatedParams?.canvasEl!;
      (canvas as any).getContext = mockGetContext;

      expect(() => {
        clearOvalCanvas({ canvas });
      }).toThrow();
    });
  });
});
