// Re-export internal apis & types of `@aws-amplify/storage/internals` in a single file
// eslint-disable-next-line import/no-extraneous-dependencies
export {
  AuthConfigAdapter,
  copy,
  CopyInput,
  createLocationCredentialsStore,
  CreateLocationCredentialsStoreInput,
  createManagedAuthConfigAdapter,
  CreateManagedAuthConfigAdapterInput,
  GetLocationCredentials,
  getUrl,
  GetUrlInput,
  list,
  ListLocations,
  ListLocationsOutput,
  ListOutput,
  ListPaginateInput,
  LocationCredentialsProvider,
  LocationCredentialsStore,
  Permission,
  remove,
  RemoveInput,
  StorageSubpathStrategy,
  uploadData,
  UploadDataInput,
} from '@aws-amplify/storage/internals';
