// Re-export internal apis & types of `@aws-amplify/storage/internals` in a single file
// eslint-disable-next-line import/no-extraneous-dependencies
export {
  AWSTemporaryCredentials,
  CopyInput,
  CredentialsLocation,
  CredentialsProvider,
  ListLocations,
  ListLocationsOutput,
  ListOutput,
  ListPaginateInput,
  LocationCredentials,
  LocationCredentialsProvider,
  Permission,
  RemoveInput,
  StorageSubpathStrategy,
  StorageValidationErrorCode,
  UploadDataInput,
  assertValidationError,
  copy,
  getDataAccess,
  getUrl,
  list,
  listCallerAccessGrants,
  remove,
  uploadData,
  validationErrorMap,
} from '@aws-amplify/storage/internals';
