# Description: This workflow automatically adds a `pending-triage` label to new issues
#
# Triggered by: newly opened or re-opened issues

name: Label issues

on:
  issues:
    types: [opened, reopened]

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add pending-triage label
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo } } = context;
            const labels = ['pending-triage'];
            github.issues.addLabels({ issue_number, owner, repo, labels });
