name: POC/Test/Node16/Setup

concurrency:
  group: e2e-${{ github.event.pull_request.id }}
  cancel-in-progress: true

on:
  pull_request_target:
    branches: [chenwz-node16-poc]
    types: [opened, synchronize, labeled]

jobs:
  install:
    runs-on: ubuntu-latest
    environment: deployment
    needs: build-test
    if: ${{ needs.setup.outputs.has-changesets != 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Setup Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install packages
        uses: ./.github/actions/install-with-retries
        with:
          skip-cypress-binary: true # publishing doesn't need cypress
