on: pull_request

jobs:
  guides:
    runs-on: ubuntu-latest
    environment: ci
    env:
      NODE_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - path: ./guides/react/protected-routes
            tags: '@guides and not @todo-guides'

    steps:
      - name: Checkout Amplify UI
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2

      - name: Restore cypress runner Cache
        uses: actions/cache@v3
        id: restore-cypress-cache
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('yarn.lock') }}
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1

      - name: Install packages
        run: yarn install
      - name: Add Amplify CLI
        run: yarn global add @aws-amplify/cli
      - name: Get CLI versions
        id: cli-version
        run: echo "::set-output name=version::$(amplify --version)"
      - name: Pull down AWS environments
        if: steps.environments-cache.outputs.cache-hit != 'true'
        run: yarn environments auth pull:email
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_AUTH }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_AUTH }}

      - name: Install guides
        run: yarn install
        working-directory: ${{ matrix.path }}

      - name: Build guides
        run: yarn build
        working-directory: ${{ matrix.path }}

      - name: Start guides site
        run: yarn start & npx wait-on -c waitOnConfig.json -t 20000 http-get://localhost:3000
        working-directory: ${{ matrix.path }}

      - name: Run E2E tests against guides
        run: yarn workspace e2e test:guides
        id: e2e
        env:
          # Override on the default value in `cypress.json` with framework-specific tag
          TAGS: '${{ matrix.tags }}'

          # Env values for testing flows
          DOMAIN: ${{ secrets.DOMAIN }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          USERNAME: ${{ secrets.USERNAME }}
          NEW_PASSWORD: ${{ secrets.NEW_PASSWORD }}
          VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
      - name: Upload videos and screenshots
        uses: actions/upload-artifact@v3
        if: ${{ failure() && steps.e2e.outcome != 'success' }}
        with:
          name: guides-cypress-error
          path: |
            packages/e2e/cypress/videos/**
            packages/e2e/cypress/screenshots/**
          retention-days: 5
