# Description: This workflow runs unit + e2e tests, then publishes UI packages
#              to a custom dist NPM tag of your choice. This is intended to run
#              on release branches (e.g. `in-app-messaging/release`).
#
# Triggered by: This runs whenever you push a commit to the specified release branch.
#
# To use: replace vue-refactor/main with your release branch name. Replace <vue-refactor> with
#         your NPM tag name.

name: Test and Publish / vue-refactor/main

on:
  # You may change this to `pull_request` if you want to run this on a PRs.
  # This can be useful for publishing hotfixes quickly to unblock customers,
  # but otherwise, we recommend to use a release branch.
  push:
    branches: [vue-refactor/main]

# This permission block is only required if you're running e2e tests.
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  # You can skip tests based on your use case.
  setup-cache:
    uses: aws-amplify/amplify-ui/.github/workflows/reusable-setup-cache.yml@vue-refactor/main
    with:
      commit: ${{ github.sha }}
      repository: ${{ github.repository }}

  unit:
    uses: aws-amplify/amplify-ui/.github/workflows/reusable-unit.yml@vue-refactor/main
    needs: setup-cache
    with:
      commit: ${{ github.sha }}
      repository: ${{ github.repository }}

  e2e:
    uses: aws-amplify/amplify-ui/.github/workflows/reusable-e2e.yml@vue-refactor/main
    needs: unit
    with:
      commit: ${{ github.sha }}
      repository: ${{ github.repository }}
    secrets:
      AUTH_E2E_ROLE_ARN: ${{ secrets.AUTH_E2E_ROLE_ARN }}
      DATASTORE_E2E_ROLE_ARN: ${{ secrets.DATASTORE_E2E_ROLE_ARN }}
      GEO_E2E_ROLE_ARN: ${{ secrets.GEO_E2E_ROLE_ARN }}
      STORAGE_E2E_ROLE_ARN: ${{ secrets.STORAGE_E2E_ROLE_ARN }}
      IN_APP_MESSAGING_E2E_ROLE_ARN: ${{ secrets.IN_APP_MESSAGING_E2E_ROLE_ARN }}
      LIVENESS_E2E_ROLE_ARN: ${{ secrets.LIVENESS_E2E_ROLE_ARN }}
      DOMAIN: ${{ secrets.DOMAIN }}
      PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
      USERNAME: ${{ secrets.USERNAME }}
      NEW_PASSWORD: ${{ secrets.NEW_PASSWORD }}
      VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
      SITE_URL: ${{ secrets.SITE_URL }}
      DOCSEARCH_DOCS_APP_ID: ${{ secrets.DOCSEARCH_DOCS_APP_ID }}
      DOCSEARCH_DOCS_API_KEY: ${{ secrets.DOCSEARCH_DOCS_API_KEY }}
      DOCSEARCH_DOCS_INDEX_NAME: ${{ secrets.DOCSEARCH_DOCS_INDEX_NAME }}

  publish:
    uses: aws-amplify/amplify-ui/.github/workflows/reusable-tagged-publish.yml@vue-refactor/main
    needs: e2e
    with:
      dist-tag: vue-refactor
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
