# Description: This workflow is a POC and does tagged release to @NPM tag

name: POC / Tagged Release / Experimental

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  publish:
    uses: ./.github/workflows/reusable-tagged-publish.yml
    with:
      dist-tag: experimental
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
