# Description: This workflow runs unit + e2e tests on `account-settings/main`.
#
# Triggered by: merge to `account-settings/main` branch

name: Test / Account Settings

on:
  push:
    branches: [account-settings/main]

jobs:
  test:
    uses: aws-amplify/amplify-ui/.github/workflows/reusable-e2e.yml@account-settings/main
    with:
      commit: ${{ github.sha }}
      repository: ${{ github.repository }}
    secrets:
      AUTH_E2E_ROLE_ARN: ${{ secrets.AUTH_E2E_ROLE_ARN }}
      DATASTORE_E2E_ROLE_ARN: ${{ secrets.DATASTORE_E2E_ROLE_ARN }}
      GEO_E2E_ROLE_ARN: ${{ secrets.GEO_E2E_ROLE_ARN }}
      STORAGE_E2E_ROLE_ARN: ${{ secrets.STORAGE_E2E_ROLE_ARN }}
      IN_APP_MESSAGING_E2E_ROLE_ARN: ${{ secrets.IN_APP_MESSAGING_E2E_ROLE_ARN }}
      DOMAIN: ${{ secrets.DOMAIN }}
      PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
      USERNAME: ${{ secrets.USERNAME }}
      NEW_PASSWORD: ${{ secrets.NEW_PASSWORD }}
      VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
      SITE_URL: ${{ secrets.SITE_URL }}
      DOCSEARCH_DOCS_APP_ID: ${{ secrets.DOCSEARCH_DOCS_APP_ID }}
      DOCSEARCH_DOCS_API_KEY: ${{ secrets.DOCSEARCH_DOCS_API_KEY }}
      DOCSEARCH_DOCS_INDEX_NAME: ${{ secrets.DOCSEARCH_DOCS_INDEX_NAME }}

  publish:
    needs: test
    uses: ./.github/workflows/reusable-tagged-publish.yml
    with:
      dist-tag: account-settings
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
