name: Publish to @geo

on:
  workflow_run:
    workflows: ['Test / geo']
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: deployment
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Install and build packages
        run: yarn --frozen-lockfile && yarn build
      - name: Bump ui and ui-react packages
        run: cp .github/changeset-presets/bump-react.md .changeset
      - name: Run changeset version to geo tag
        run: yarn changeset version --snapshot geo-$(git rev-parse --short=7 HEAD) && yarn angular build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish to geo tag
        run: yarn changeset publish --tag geo
