# Description: this is a reusable workflow that runs unit and e2e tests.
#
# See `./test-prs.yml` to see an example usage.

on:
  workflow_call:
    inputs:
      dist-tag:
        # commit to run tests against
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - name: fail this workflow if dist-tag is invalid
        if: ${{ inputs.dist-tag == '' || inputs.dist-tag == 'latest' }}
        run: exit 1
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Node.js 24
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: 'yarn'
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
      - name: Install packages
        uses: ./.github/actions/install-with-retries
        with:
          skip-cypress-binary: true # publishing doesn't need cypress
      - name: Build packages
        run: yarn build
      - name: Add changeset that bumps all public packages
        # There needs to be a changeset for @aws-amplify/ui[-framework] to publish.
        run: cp .github/changeset-presets/bump-versions.md .changeset
      - name: Run changeset version to next tag
        run: yarn changeset version --snapshot ${{ inputs.dist-tag }}-$(git rev-parse --short=7 HEAD) && yarn angular build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish to next tag
        run: yarn changeset publish --tag ${{ inputs.dist-tag }}
