# Description: this is a reusable workflow that sets up cache for unit and e2e testss.

on:
  workflow_call:
    inputs:
      commit:
        # commit to run tests against
        required: true
        type: string
      repository:
        # repository to run tests against (possibly a fork of amplify-ui)
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Amplify UI
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.commit }}
          repository: ${{ inputs.repository }}
          persist-credentials: false
      - name: Setup Node.js 24
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: 'yarn'
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
      - name: Restore cypress runner from Cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: restore-cypress-cache
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('yarn.lock') }}
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1
      - name: Restore Puppeteer runner from Cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: restore-puppeteer-cache
        with:
          path: ~/.cache/puppeteer
          key: ${{ runner.os }}-puppeteer-${{ hashFiles('yarn.lock') }}
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1
      - name: Restore node_modules from Cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: restore-node-modules-cache
        with:
          path: |
            ./node_modules
            **/node_modules
          key: ${{ runner.os }}-nodemodules-${{ hashFiles('yarn.lock') }}
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 3
      - name: Install packages
        if: steps.restore-node-modules-cache.outputs.cache-hit != 'true'
        uses: ./.github/actions/install-with-retries
        with:
          # only install binary if cypress cache missed
          skip-cypress-binary: ${{ steps.restore-cypress-cache.outputs.cache-hit }}
      - name: Restore packages/ui/dist from Cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: restore-ui-cache
        with:
          path: ./packages/ui/dist
          key: ${{ runner.os }}-ui-${{ inputs.commit }}
      - name: Build ui package
        if: steps.restore-ui-cache.outputs.cache-hit != 'true'
        run: yarn ui build
