# Description: This is a POC for running the React Native canaries

name: POC / React Native Canary

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: sparkfabrik/ios-build-action@v2.0.0
    with:
      build-pods: true
      pods-path: 'ios/Podfile'
      configuration: Debug
      export-method: app-store
      workspace-path: ./canary/apps/react-native/canarytest/ios/canarytest.xcworkspace
      project-path: ./canary/apps/react-native/canarytest/ios/canarytest.xcodeproj

      # - name: run tests
      #   uses: reactivecircus/android-emulator-runner@v2
      #   with:
      #     api-level: 29
      #     script: ./gradlew connectedCheck

      # - name: Use Node.js v16
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 16.x
      # - name: Run yarn install on sample app
      #   run: yarn install
      #   working-directory: ./canary/apps/react-native/canarytest
      # - name: Build Android apk (debug)
      #   run: ./gradlew assembleDebug -Dorg.gradle.logging.level=info
      #   working-directory: ./canary/apps/react-native/canarytest
