# Description: This is a POC for running the React Native canaries

name: POC / React Native Canary

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run yarn install on sample app
        run: yarn install
        working-directory: ./canary/apps/react-native/canarytest
      - name: Run sample app on Android
        run: yarn android
        working-directory: ./canary/apps/react-native/canarytest
