# Description: this workflow creates or updates the "Version Packages" PR.
#
# Triggered by: whenever a commit is merged onto main and there are
#               new changesets to consume.

name: Version Packages

on:
  push:
    branches: [main, hotfix]

permissions:
  contents: write # Used to commit to "Version Packages" PR
  pull-requests: write # Used to create "Version Packages" PR
  # Other permissions are defaulted to none

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Check if repo has unconsumed changesets
        id: has-changesets
        uses: ./.github/actions/has-changesets
      - name: Setup Node.js 24
        if: ${{ steps.has-changesets.outputs.has-changesets == 'true' }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: 'yarn'
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 2
      - name: Install packages
        if: ${{ steps.has-changesets.outputs.has-changesets == 'true' }}
        run: yarn --frozen-lockfile
      - name: Create or update Version Packages PR
        if: ${{ steps.has-changesets.outputs.has-changesets == 'true' }}
        uses: changesets/action@aba318e9165b45b7948c60273e0b72fce0a64eb9 #v1.4.7
        with:
          version: yarn bumpVersions
          # Use the current branch as the base for the PR
          base: ${{ github.ref_name }}
          # Custom title based on branch
          title: 'Version Packages (${{ github.ref_name }})'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
