# This workflow will run unit, e2e, and docs tests on PRs targeted against `main`.

name: Check NPM version

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, labeled]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: 'yarn'
      - name: Check npm version
        run: npm --version
